from __future__ import annotations

"""Operations, messaging, and commercial reconciliation domain-risk patterns for alignment traceability."""

ANALYTICS_EVENT_INTEGRITY_PATTERN = (
    r"\b(?:analytics|telemetry|instrumentation|tracking|event[- ]?schema|event\s+payload|"
    r"analytics[- ]?events?|funnel|warehouse|clickstream|segment\.com|segment[- ]?(?:event|analytics|tracking)|"
    r"amplitude|mixpanel|ga4|"
    r"event[- ]?integrity)\b"
    r"|埋点|数据埋点|事件上报|事件\s*schema|事件结构|事件载荷|漏斗|分析事件|数仓|数据仓库|点击流|上报"
)
EXPERIMENT_ASSIGNMENT_CONSISTENCY_PATTERN = (
    r"\b(?:a/b|ab[- ]?test|split[- ]?test|experiment(?:s)?|variant|assignment|exposure|"
    r"feature[- ]?flag|treatment|control[- ]?group|bucket(?:ing)?)\b"
    r"|A/B|AB\s*实验|实验曝光|实验分流|实验分桶|实验分组|实验组|对照组|分桶|变体"
)
ASYNC_JOB_LIFECYCLE_PATTERN = (
    r"\b(?:async[- ]?job|background[- ]?(?:job|worker)|job[- ]?queue|queued[- ]?job|"
    r"worker(?:s)?|job[- ]?status|job[- ]?lifecycle|persist(?:ed|ent)?[- ]?(?:job|queue)|"
    r"pending/running/succeeded/failed|pending[- ]?running[- ]?succeeded[- ]?failed)\b"
    r"|异步任务|后台任务|任务队列|后台\s*worker|入队|出队|持久化入队|任务状态|任务生命周期|"
    r"pending/running/succeeded/failed|待处理/运行中/成功/失败"
)
QUEUE_FAILURE_RECOVERY_PATTERN = (
    r"\b(?:dead[- ]?letter|deadletter|dlq|poison[- ]?message|failure[- ]?queue|failed[- ]?jobs?|"
    r"recoverable[- ]?queue|requeue|resume|resumable|refresh[- ]?recovery|job[- ]?recovery|"
    r"retry[- ]?budget)\b"
    r"|死信|死信队列|失败队列|失败任务|可恢复队列|重新入队|恢复队列|状态恢复|断线刷新|刷新恢复"
)
SCHEDULE_TIMEZONE_RECURRENCE_PATTERN = (
    r"(?:(?:\b(?:schedul(?:e|ed|er|ing)|scheduled[- ]?job|cron|cron[- ]?expression|recurr(?:ing|ence)?|"
    r"recurring[- ]?job|periodic[- ]?job|digest[- ]?scheduler|calendar[- ]?job)\b|定时|定期|调度|周期任务|"
    r"周期执行|重复执行|定时发送|定时任务).{0,180}"
    r"(?:\b(?:time[- ]?zone|timezone|local[- ]?time|dst|daylight[- ]?saving|missed[- ]?run|"
    r"catch[- ]?up|catchup|backfill|skipped[- ]?run|scheduled[- ]?at|sent[- ]?at|"
    r"run[- ]?window|calendar[- ]?boundary)\b|时区|本地时间|用户本地时间|夏令时|错过执行|漏执行|补偿|补发|"
    r"只补一次|执行窗口|调度时间|发送时间)"
    r"|(?:\b(?:time[- ]?zone|timezone|local[- ]?time|dst|daylight[- ]?saving|missed[- ]?run|"
    r"catch[- ]?up|catchup|backfill|skipped[- ]?run|scheduled[- ]?at|sent[- ]?at|"
    r"run[- ]?window|calendar[- ]?boundary)\b|时区|本地时间|用户本地时间|夏令时|错过执行|漏执行|补偿|补发|"
    r"只补一次|执行窗口|调度时间|发送时间).{0,180}"
    r"(?:\b(?:schedul(?:e|ed|er|ing)|scheduled[- ]?job|cron|cron[- ]?expression|recurr(?:ing|ence)?|"
    r"recurring[- ]?job|periodic[- ]?job|digest[- ]?scheduler|calendar[- ]?job)\b|定时|定期|调度|周期任务|"
    r"周期执行|重复执行|定时发送|定时任务))"
)
WEBHOOK_SIGNATURE_REPLAY_ORDERING_PATTERN = (
    r"(?:(?:\b(?:webhook(?:s)?|webhook[- ]?signature|signed[- ]?webhook(?:s)?|provider[- ]?event(?:s)?|"
    r"stripe[- ]?(?:signature|event)|signed[- ]?event(?:s)?)\b|webhook|供应商事件|provider事件|"
    r"签名事件|Stripe\s*事件).{0,220}"
    r"(?:\b(?:event[- ]?replay|replay(?:ed)?[- ]?event(?:s)?|signature[- ]?(?:verification|verified|validation)|"
    r"out[- ]?of[- ]?order|event[- ]?ordering|ordering[- ]?proof|duplicate[- ]?event(?:s)?)\b|"
    r"事件重放|重放事件|签名验证|签名校验|事件签名|乱序|事件乱序|事件顺序|重复事件)"
    r"|(?:\b(?:event[- ]?replay|replay(?:ed)?[- ]?event(?:s)?|signature[- ]?(?:verification|verified|validation)|"
    r"out[- ]?of[- ]?order|event[- ]?ordering|ordering[- ]?proof|duplicate[- ]?event(?:s)?)\b|"
    r"事件重放|重放事件|签名验证|签名校验|事件签名|乱序|事件乱序|事件顺序|重复事件).{0,220}"
    r"(?:\b(?:webhook(?:s)?|webhook[- ]?signature|signed[- ]?webhook(?:s)?|provider[- ]?event(?:s)?|"
    r"stripe[- ]?(?:signature|event)|signed[- ]?event(?:s)?)\b|webhook|供应商事件|provider事件|"
    r"签名事件|Stripe\s*事件))"
)
BILLING_LEDGER_RECONCILIATION_PATTERN = (
    r"\b(?:billing[- ]?ledger|ledger[- ]?reconciliation|invoice[- ]?reconciliation|subscription[- ]?reconciliation|"
    r"entitlement(?:s)?|entitlement[- ]?sync|provider[- ]?ledger|stripe[- ]?(?:dashboard|fixture)|"
    r"invoice[- ]?amount|subscription[- ]?state|subscription[- ]?status)\b"
    r"|账本对账|台账对账|账务对账|发票对账|订阅对账|订阅权限|权益同步|本地账本|本地台账|发票金额|订阅状态|Stripe\s*对账"
)
DISPUTE_CHARGEBACK_LIFECYCLE_PATTERN = (
    r"(?:(?:\b(?:payment[- ]?dispute(?:s)?|dispute[- ]?lifecycle|chargeback[- ]?lifecycle|"
    r"chargeback(?:s)?|retrieval[- ]?request(?:s)?|representment|dispute[- ]?evidence|"
    r"evidence[- ]?submission|evidence[- ]?package|issuer|acquirer|reason[- ]?code(?:s)?|"
    r"provisional[- ]?(?:credit|debit)|partial[- ]?dispute|duplicate[- ]?dispute|"
    r"refund[- ]?overlap|dispute[- ]?webhook(?:s)?|dispute[- ]?id)\b|"
    r"支付争议|付款争议|拒付生命周期|争议生命周期|拒付|争议扣款|调单请求|调单|再请款|"
    r"争议证据|证据提交|证据包|发卡行|收单行|原因码|临时贷记|临时扣记|部分争议|重复争议|"
    r"退款重叠|争议\s*webhook|争议\s*id).{0,360}"
    r"(?:\b(?:dispute\.created|dispute\.updated|dispute\.closed|provider[- ]?dispute[- ]?id|"
    r"provider[- ]?fixture(?:s)?|webhook[- ]?signature|webhook[- ]?replay|out[- ]?of[- ]?order|"
    r"submission[- ]?deadline|deadline[- ]?scheduler|merchant[- ]?response[- ]?sla|"
    r"order[- ]?fulfillment[- ]?evidence|customer[- ]?notification|notification[- ]?delivery|"
    r"win|won|loss|lost|closed|happy[- ]?path[- ]?close|stripe[- ]?dashboard|"
    r"balance[- ]?adjustment|invoice[- ]?adjustment|ledger[- ]?entries?|payout[- ]?hold|"
    r"payout[- ]?release|audit[- ]?trail|stale[- ]?dispute|failed[- ]?dispute[- ]?alert(?:s)?)\b|"
    r"争议创建|争议更新|争议关闭|供应商争议\s*id|供应商样本|webhook\s*签名|"
    r"webhook\s*重放|乱序|提交截止|截止调度|商户响应\s*SLA|履约证据|客户通知|通知送达|"
    r"胜诉|败诉|关闭|happy\s*path\s*关闭|Stripe\s*dashboard|余额调整|发票调整|账本分录|"
    r"打款冻结|打款放行|审计轨迹|过期争议|卡住的争议|争议失败告警)"
    r"|(?:\b(?:dispute\.created|dispute\.updated|dispute\.closed|provider[- ]?dispute[- ]?id|"
    r"provider[- ]?fixture(?:s)?|webhook[- ]?signature|webhook[- ]?replay|out[- ]?of[- ]?order|"
    r"submission[- ]?deadline|deadline[- ]?scheduler|merchant[- ]?response[- ]?sla|"
    r"order[- ]?fulfillment[- ]?evidence|customer[- ]?notification|notification[- ]?delivery|"
    r"win|won|loss|lost|closed|happy[- ]?path[- ]?close|stripe[- ]?dashboard|"
    r"balance[- ]?adjustment|invoice[- ]?adjustment|ledger[- ]?entries?|payout[- ]?hold|"
    r"payout[- ]?release|audit[- ]?trail|stale[- ]?dispute|failed[- ]?dispute[- ]?alert(?:s)?)\b|"
    r"争议创建|争议更新|争议关闭|供应商争议\s*id|供应商样本|webhook\s*签名|"
    r"webhook\s*重放|乱序|提交截止|截止调度|商户响应\s*SLA|履约证据|客户通知|通知送达|"
    r"胜诉|败诉|关闭|happy\s*path\s*关闭|Stripe\s*dashboard|余额调整|发票调整|账本分录|"
    r"打款冻结|打款放行|审计轨迹|过期争议|卡住的争议|争议失败告警).{0,360}"
    r"(?:\b(?:payment[- ]?dispute(?:s)?|dispute[- ]?lifecycle|chargeback[- ]?lifecycle|"
    r"chargeback(?:s)?|retrieval[- ]?request(?:s)?|representment|dispute[- ]?evidence|"
    r"evidence[- ]?submission|evidence[- ]?package|issuer|acquirer|reason[- ]?code(?:s)?|"
    r"provisional[- ]?(?:credit|debit)|partial[- ]?dispute|duplicate[- ]?dispute|"
    r"refund[- ]?overlap|dispute[- ]?webhook(?:s)?|dispute[- ]?id)\b|"
    r"支付争议|付款争议|拒付生命周期|争议生命周期|拒付|争议扣款|调单请求|调单|再请款|"
    r"争议证据|证据提交|证据包|发卡行|收单行|原因码|临时贷记|临时扣记|部分争议|重复争议|"
    r"退款重叠|争议\s*webhook|争议\s*id))"
)
PAYOUT_SETTLEMENT_RECONCILIATION_PATTERN = (
    r"(?:(?:\b(?:marketplace[- ]?payout(?:s)?|seller[- ]?payout(?:s)?|merchant[- ]?payout(?:s)?|"
    r"payout[- ]?batch(?:es)?|payout(?:s)?|seller[- ]?balance|merchant[- ]?balance|"
    r"provider[- ]?transfer(?:s)?|bank[- ]?transfer(?:s)?|connected[- ]?account(?:s)?)\b|"
    r"卖家打款|商家打款|商户打款|卖家结算|商家结算|商户结算|提现批次|打款批次|"
    r"打款|付款批次|卖家余额|商家余额|商户余额|供应商转账|银行转账|连接账户).{0,360}"
    r"(?:\b(?:seller[- ]?balance[- ]?ledger|balance[- ]?ledger|platform[- ]?fee|"
    r"chargeback(?:s)?|adjustment(?:s)?|hold(?:s)?|reserve(?:s)?|negative[- ]?balance|"
    r"payout[- ]?batch[- ]?cutoff|cutoff|fx[- ]?round(?:ing)?|currency[- ]?round(?:ing)?|"
    r"provider[- ]?transfer[- ]?id|bank[- ]?account|kyc[- ]?hold|failed[- ]?payout|failed[- ]?transfer|"
    r"payout[- ]?retry|reversal(?:s)?|double[- ]?payout|payout[- ]?report|bank[- ]?statement|"
    r"stuck[- ]?payout|reconciliation[- ]?mismatch|ledger[- ]?entry[- ]?id|payout[- ]?batch[- ]?id)\b|"
    r"卖家余额账本|商家余额账本|商户余额账本|平台费|拒付|争议扣款|调账|调整|"
    r"资金冻结|保证金|准备金|负余额|批次截断|批次截止|汇率取整|币种取整|"
    r"供应商转账\s*id|银行账户|KYC\s*冻结|打款失败|转账失败|打款重试|冲正|撤销转账|"
    r"重复打款|双重打款|打款报表|银行流水|银行对账单|卡住的打款|对账不一致|"
    r"账本分录\s*id|打款批次\s*id)"
    r"|(?:\b(?:seller[- ]?balance[- ]?ledger|balance[- ]?ledger|platform[- ]?fee|"
    r"chargeback(?:s)?|adjustment(?:s)?|hold(?:s)?|reserve(?:s)?|negative[- ]?balance|"
    r"payout[- ]?batch[- ]?cutoff|cutoff|fx[- ]?round(?:ing)?|currency[- ]?round(?:ing)?|"
    r"provider[- ]?transfer[- ]?id|bank[- ]?account|kyc[- ]?hold|failed[- ]?payout|failed[- ]?transfer|"
    r"payout[- ]?retry|reversal(?:s)?|double[- ]?payout|payout[- ]?report|bank[- ]?statement|"
    r"stuck[- ]?payout|reconciliation[- ]?mismatch|ledger[- ]?entry[- ]?id|payout[- ]?batch[- ]?id)\b|"
    r"卖家余额账本|商家余额账本|商户余额账本|平台费|拒付|争议扣款|调账|调整|"
    r"资金冻结|保证金|准备金|负余额|批次截断|批次截止|汇率取整|币种取整|"
    r"供应商转账\s*id|银行账户|KYC\s*冻结|打款失败|转账失败|打款重试|冲正|撤销转账|"
    r"重复打款|双重打款|打款报表|银行流水|银行对账单|卡住的打款|对账不一致|"
    r"账本分录\s*id|打款批次\s*id).{0,360}"
    r"(?:\b(?:marketplace[- ]?payout(?:s)?|seller[- ]?payout(?:s)?|merchant[- ]?payout(?:s)?|"
    r"payout[- ]?batch(?:es)?|payout(?:s)?|seller[- ]?balance|merchant[- ]?balance|"
    r"provider[- ]?transfer(?:s)?|bank[- ]?transfer(?:s)?|connected[- ]?account(?:s)?)\b|"
    r"卖家打款|商家打款|商户打款|卖家结算|商家结算|商户结算|提现批次|打款批次|"
    r"打款|付款批次|卖家余额|商家余额|商户余额|供应商转账|银行转账|连接账户))"
)
METRIC_REPORTING_RECONCILIATION_PATTERN = (
    r"(?:(?:\b(?:mrr|arr|monthly[- ]?recurring[- ]?revenue|annual[- ]?recurring[- ]?revenue|"
    r"revenue[- ]?(?:dashboard|report|segment)|metric(?:s)?[- ]?(?:definition|version|reporting)?|"
    r"dashboard[- ]?metric|reporting[- ]?metric|kpi)\b|"
    r"收入看板|收入报表|收入分组|指标口径|指标定义|指标版本|指标).{0,320}"
    r"(?:\b(?:metric[- ]?definition|definition[- ]?version|metric[- ]?version|reconciliation|"
    r"ledger[- ]?reconciliation|invoice[- ]?reconciliation|provider[- ]?reconciliation|currency|fx|"
    r"exchange[- ]?rate|exchange[- ]?rate[- ]?date|cutoff|month[- ]?cutoff|timezone|time[- ]?zone|"
    r"proration|refund|discount|coupon|trial|downgrade|upgrade|paused[- ]?subscription|backfill|"
    r"historical[- ]?backfill|locked[- ]?month|restate|revenue[- ]?segment)\b|"
    r"对账|账本|台账|发票|供应商对账|币种|汇率|汇率日期|时区|截断|月结|试用|优惠券|折扣|"
    r"退款|按比例计费|升级|降级|暂停订阅|回填|历史回填|锁账|旧月锁账|重算|收入分组)"
    r"|(?:\b(?:metric[- ]?definition|definition[- ]?version|metric[- ]?version|reconciliation|"
    r"ledger[- ]?reconciliation|invoice[- ]?reconciliation|provider[- ]?reconciliation|currency|fx|"
    r"exchange[- ]?rate|exchange[- ]?rate[- ]?date|cutoff|month[- ]?cutoff|timezone|time[- ]?zone|"
    r"proration|refund|discount|coupon|trial|downgrade|upgrade|paused[- ]?subscription|backfill|"
    r"historical[- ]?backfill|locked[- ]?month|restate|revenue[- ]?segment)\b|"
    r"对账|账本|台账|发票|供应商对账|币种|汇率|汇率日期|时区|截断|月结|试用|优惠券|折扣|"
    r"退款|按比例计费|升级|降级|暂停订阅|回填|历史回填|锁账|旧月锁账|重算|收入分组).{0,320}"
    r"(?:\b(?:mrr|arr|monthly[- ]?recurring[- ]?revenue|annual[- ]?recurring[- ]?revenue|"
    r"revenue[- ]?(?:dashboard|report|segment)|metric(?:s)?[- ]?(?:definition|version|reporting)?|"
    r"dashboard[- ]?metric|reporting[- ]?metric|kpi)\b|"
    r"收入看板|收入报表|收入分组|指标口径|指标定义|指标版本|指标))"
)
NOTIFICATION_SUBSCRIPTION_DELIVERABILITY_PATTERN = (
    r"\b(?:unsubscribe|unsubscribed|subscription[- ]?preference(?:s)?|preference[- ]?center|"
    r"email[- ]?preference(?:s)?|opt[- ]?(?:out|in)|suppression[- ]?list|suppressed|"
    r"bounce(?:d)?|complaint(?:s)?|spam[- ]?complaint(?:s)?|deliverability|delivery[- ]?event(?:s)?|"
    r"provider[- ]?delivery|message[- ]?delivery|sendgrid|mailgun|ses)\b"
    r"|退订|取消订阅|订阅偏好|偏好中心|邮件偏好|抑制名单|抑制列表|退信|投诉|垃圾邮件投诉|"
    r"送达|投递|送达事件|投递事件|送达率|邮件服务商"
)
