from __future__ import annotations

"""Compatibility aggregate for Agent-candidate traceability category catalogs."""

from loopora.alignment_traceability_candidate_execution_catalog import (
    EXECUTION_STRATEGY_CATEGORY_PATTERNS,
    EXECUTION_STRATEGY_MARKER_PATTERNS,
)

from loopora.alignment_traceability_candidate_residual_risk_catalog import (
    NO_ACCEPTED_RESIDUAL_RISK_BUNDLE_PATTERN,
    NO_ACCEPTED_RESIDUAL_RISK_TASK_PATTERN,
    RESIDUAL_RISK_BASE_CATEGORY,
    RESIDUAL_RISK_POLICY_CATEGORY_PATTERNS,
    RESIDUAL_RISK_POLICY_MARKER_PATTERNS,
)

from loopora.alignment_traceability_candidate_success_surface_catalog import (
    SUCCESS_SURFACE_BASE_CATEGORY,
    SUCCESS_SURFACE_CATEGORY_PATTERNS,
    SUCCESS_SURFACE_MARKER_PATTERNS,
)

from loopora.alignment_traceability_candidate_tradeoff_catalog import (
    TRADEOFF_CATEGORY_PATTERNS,
    TRADEOFF_MARKER_PATTERNS,
)

__all__ = (
    "EXECUTION_STRATEGY_CATEGORY_PATTERNS",
    "EXECUTION_STRATEGY_MARKER_PATTERNS",
    "NO_ACCEPTED_RESIDUAL_RISK_BUNDLE_PATTERN",
    "NO_ACCEPTED_RESIDUAL_RISK_TASK_PATTERN",
    "RESIDUAL_RISK_BASE_CATEGORY",
    "RESIDUAL_RISK_POLICY_CATEGORY_PATTERNS",
    "RESIDUAL_RISK_POLICY_MARKER_PATTERNS",
    "SUCCESS_SURFACE_BASE_CATEGORY",
    "SUCCESS_SURFACE_CATEGORY_PATTERNS",
    "SUCCESS_SURFACE_MARKER_PATTERNS",
    "TRADEOFF_CATEGORY_PATTERNS",
    "TRADEOFF_MARKER_PATTERNS",
)
