from __future__ import annotations

"""KYC, AML, and sanctions-screening domain-risk patterns."""

KYC_AML_SANCTIONS_SCREENING_PATTERN = (
    r"(?:(?:\b(?:kyc|kyb|aml|customer[- ]?due[- ]?diligence|enhanced[- ]?due[- ]?diligence|"
    r"identity[- ]?verification|business[- ]?verification|business[- ]?registry|beneficial[- ]?owner(?:s)?|"
    r"document[- ]?(?:ocr|verification)|liveness|address[- ]?verification|"
    r"sanctions?[- ]?screening|sanctions?[- ]?list|pep|politically[- ]?exposed[- ]?person|"
    r"adverse[- ]?media|watchlist[- ]?screening|watchlist|risk[- ]?score|manual[- ]?review[- ]?queue|"
    r"rescreen(?:ing)?|periodic[- ]?rescreen(?:ing)?|appeal|resubmission)\b|"
    r"实名认证|企业认证|商户认证|身份核验|企业核验|工商登记|受益所有人|实益拥有人|"
    r"证件\s*OCR|证件核验|活体检测|地址核验|反洗钱|制裁筛查|制裁名单|PEP|政治公众人物|"
    r"负面媒体|观察名单|名单筛查|风险评分|人工复核队列|人工审核队列|定期复筛|重新筛查|申诉|重新提交).{0,360}"
    r"(?:\b(?:provider[- ]?sandbox|sandbox[- ]?approved|provider[- ]?status|ui[- ]?verified|"
    r"approved|rejected|manual[- ]?review|false[- ]?positive|false[- ]?negative|expired[- ]?document|"
    r"fraudulent[- ]?document|decision[- ]?reason(?:s)?|reason[- ]?code(?:s)?|audit[- ]?trail|"
    r"webhook[- ]?signature|webhook[- ]?replay|out[- ]?of[- ]?order|idempotenc(?:y|e)|"
    r"payout[- ]?hold|payout[- ]?release|hold[- ]?release|ledger[- ]?reconciliation|"
    r"retention|region[- ]?retention|monitoring[- ]?alerts?)\b|"
    r"沙箱通过|供应商状态|界面显示已认证|已认证|通过|拒绝|人工复核|人工审核|误报|漏报|"
    r"过期证件|欺诈证件|欺诈文件|决策原因|原因码|审计轨迹|审计日志|webhook\s*签名|"
    r"webhook\s*重放|乱序|幂等|打款冻结|打款放行|付款冻结|付款放行|冻结释放|账本对账|"
    r"区域留存|留存|监控告警)"
    r"|(?:\b(?:provider[- ]?sandbox|sandbox[- ]?approved|provider[- ]?status|ui[- ]?verified|"
    r"approved|rejected|manual[- ]?review|false[- ]?positive|false[- ]?negative|expired[- ]?document|"
    r"fraudulent[- ]?document|decision[- ]?reason(?:s)?|reason[- ]?code(?:s)?|audit[- ]?trail|"
    r"webhook[- ]?signature|webhook[- ]?replay|out[- ]?of[- ]?order|idempotenc(?:y|e)|"
    r"payout[- ]?hold|payout[- ]?release|hold[- ]?release|ledger[- ]?reconciliation|"
    r"retention|region[- ]?retention|monitoring[- ]?alerts?)\b|"
    r"沙箱通过|供应商状态|界面显示已认证|已认证|通过|拒绝|人工复核|人工审核|误报|漏报|"
    r"过期证件|欺诈证件|欺诈文件|决策原因|原因码|审计轨迹|审计日志|webhook\s*签名|"
    r"webhook\s*重放|乱序|幂等|打款冻结|打款放行|付款冻结|付款放行|冻结释放|账本对账|"
    r"区域留存|留存|监控告警).{0,360}"
    r"(?:\b(?:kyc|kyb|aml|customer[- ]?due[- ]?diligence|enhanced[- ]?due[- ]?diligence|"
    r"identity[- ]?verification|business[- ]?verification|business[- ]?registry|beneficial[- ]?owner(?:s)?|"
    r"document[- ]?(?:ocr|verification)|liveness|address[- ]?verification|"
    r"sanctions?[- ]?screening|sanctions?[- ]?list|pep|politically[- ]?exposed[- ]?person|"
    r"adverse[- ]?media|watchlist[- ]?screening|watchlist|risk[- ]?score|manual[- ]?review[- ]?queue|"
    r"rescreen(?:ing)?|periodic[- ]?rescreen(?:ing)?|appeal|resubmission)\b|"
    r"实名认证|企业认证|商户认证|身份核验|企业核验|工商登记|受益所有人|实益拥有人|"
    r"证件\s*OCR|证件核验|活体检测|地址核验|反洗钱|制裁筛查|制裁名单|PEP|政治公众人物|"
    r"负面媒体|观察名单|名单筛查|风险评分|人工复核队列|人工审核队列|定期复筛|重新筛查|申诉|重新提交))"
)


__all__ = ("KYC_AML_SANCTIONS_SCREENING_PATTERN",)
