from __future__ import annotations

"""Compatibility aggregate for alignment traceability term catalogs."""

from loopora.alignment_traceability_agent_term_catalog import (
    ALIGNMENT_AGENT_CANDIDATE_GENERIC_TERMS as ALIGNMENT_AGENT_CANDIDATE_GENERIC_TERMS,
)
from loopora.alignment_traceability_cjk_term_catalog import (
    ALIGNMENT_TRACEABILITY_CJK_DOMAIN_TERMS as ALIGNMENT_TRACEABILITY_CJK_DOMAIN_TERMS,
    ALIGNMENT_TRACEABILITY_CJK_STOP_CHARS as ALIGNMENT_TRACEABILITY_CJK_STOP_CHARS,
    ALIGNMENT_TRACEABILITY_GENERIC_CJK_TERMS as ALIGNMENT_TRACEABILITY_GENERIC_CJK_TERMS,
)
from loopora.alignment_traceability_generic_term_catalog import (
    ALIGNMENT_LOOP_FIT_TRACEABILITY_GENERIC_TERMS as ALIGNMENT_LOOP_FIT_TRACEABILITY_GENERIC_TERMS,
    ALIGNMENT_TRACEABILITY_GENERIC_TERMS as ALIGNMENT_TRACEABILITY_GENERIC_TERMS,
)

__all__ = [
    "ALIGNMENT_AGENT_CANDIDATE_GENERIC_TERMS",
    "ALIGNMENT_LOOP_FIT_TRACEABILITY_GENERIC_TERMS",
    "ALIGNMENT_TRACEABILITY_CJK_DOMAIN_TERMS",
    "ALIGNMENT_TRACEABILITY_CJK_STOP_CHARS",
    "ALIGNMENT_TRACEABILITY_GENERIC_CJK_TERMS",
    "ALIGNMENT_TRACEABILITY_GENERIC_TERMS",
]
