from __future__ import annotations

"""Compatibility aggregate for trust-family domain-risk patterns."""

from loopora.alignment_traceability_domain_patterns_trust_access import (
    AUTHORIZATION_POLICY_CONSISTENCY_PATTERN,
    DATA_RESIDENCY_REGIONAL_ISOLATION_PATTERN,
    SUPPORT_IMPERSONATION_BREAKGLASS_PATTERN,
    TENANT_ISOLATION_PATTERN,
)
from loopora.alignment_traceability_domain_patterns_trust_compliance import (
    KYC_AML_SANCTIONS_SCREENING_PATTERN,
)
from loopora.alignment_traceability_domain_patterns_trust_identity import (
    AUTH_SESSION_TOKEN_LIFECYCLE_PATTERN,
    IDENTITY_PROVISIONING_ROLE_MAPPING_PATTERN,
    IDENTITY_SSO_ASSERTION_PATTERN,
    KEY_ROTATION_SECRET_LIFECYCLE_PATTERN,
)
from loopora.alignment_traceability_domain_patterns_trust_inclusion import (
    ACCESSIBILITY_A11Y_PATTERN,
    LOCALE_I18N_PATTERN,
)

__all__ = (
    "ACCESSIBILITY_A11Y_PATTERN",
    "AUTHORIZATION_POLICY_CONSISTENCY_PATTERN",
    "AUTH_SESSION_TOKEN_LIFECYCLE_PATTERN",
    "DATA_RESIDENCY_REGIONAL_ISOLATION_PATTERN",
    "IDENTITY_PROVISIONING_ROLE_MAPPING_PATTERN",
    "IDENTITY_SSO_ASSERTION_PATTERN",
    "KEY_ROTATION_SECRET_LIFECYCLE_PATTERN",
    "KYC_AML_SANCTIONS_SCREENING_PATTERN",
    "LOCALE_I18N_PATTERN",
    "SUPPORT_IMPERSONATION_BREAKGLASS_PATTERN",
    "TENANT_ISOLATION_PATTERN",
)
