from __future__ import annotations

"""Tenant, authorization, residency, and support-access domain-risk patterns."""

TENANT_ISOLATION_PATTERN = (
    r"\b(?:tenant[- ]?isolation|cross[- ]?tenant|direct[- ]?object[- ]?id|object[- ]?id|idor|"
    r"row[- ]?level[- ]?security|rls|role[- ]?matrix|owner/member/viewer|org\s+[ab]|"
    r"tenant[- ]?domain[- ]?binding|domain[- ]?binding|tenant[- ]?access|seller[- ]?tenant)\b"
    r"|租户隔离|跨租户|直接对象\s*ID|对象\s*ID|越权|行级权限|行级安全|角色矩阵|组织隔离|租户域名|域名绑定|串租户|串数据|租户访问"
)


AUTHORIZATION_POLICY_CONSISTENCY_PATTERN = (
    r"(?:(?:\b(?:authorization[- ]?policy|policy[- ]?(?:engine|decision|version|evaluation)|"
    r"rbac|abac|role[- ]?hierarchy|resource[- ]?scope|team[- ]?membership|"
    r"owner/admin/viewer|deny[- ]?overrides[- ]?allow|field[- ]?level[- ]?permissions?|"
    r"permission[- ]?matrix|access[- ]?matrix|authorization[- ]?matrix|"
    r"policy[- ]?decision[- ]?trace|pdp|pep|opa|casbin)\b|"
    r"授权策略|权限策略|策略引擎|策略决策|策略版本|策略评估|RBAC|ABAC|"
    r"角色层级|资源范围|团队成员关系|拒绝优先|字段级权限|权限矩阵|访问矩阵|授权矩阵|"
    r"策略决策追踪|策略决策链).{0,320}"
    r"(?:\b(?:api[- ]?endpoint(?:s)?|endpoint[- ]?enforcement|ui[- ]?affordance(?:s)?|"
    r"background[- ]?job(?:s)?|export(?:s)?|report(?:s)?|audit[- ]?log|"
    r"role[- ]?change(?:s)?|group[- ]?mapping|scim|sso|temporary[- ]?permission(?:s)?|"
    r"policy[- ]?version[- ]?rollout|cache[- ]?invalidation|cache[- ]?stale|revocation|"
    r"negative[- ]?authorization[- ]?cases?|cross[- ]?resource[- ]?escalation|"
    r"middleware|hidden[- ]?button|hide[- ]?button|happy[- ]?path[- ]?endpoint|"
    r"admin[- ]?role)\b|"
    r"API\s*端点|端点强制|界面入口|后台任务|异步任务|导出|报表|审计日志|"
    r"角色变更|组映射|临时权限|策略版本发布|缓存失效|缓存陈旧|撤销|吊销|"
    r"负向授权|跨资源提权|只隐藏按钮|隐藏按钮|只加中间件|中间件|只检查管理员|"
    r"只检查\s*admin|happy\s*path\s*端点)"
    r"|(?:\b(?:api[- ]?endpoint(?:s)?|endpoint[- ]?enforcement|ui[- ]?affordance(?:s)?|"
    r"background[- ]?job(?:s)?|export(?:s)?|report(?:s)?|audit[- ]?log|"
    r"role[- ]?change(?:s)?|group[- ]?mapping|scim|sso|temporary[- ]?permission(?:s)?|"
    r"policy[- ]?version[- ]?rollout|cache[- ]?invalidation|cache[- ]?stale|revocation|"
    r"negative[- ]?authorization[- ]?cases?|cross[- ]?resource[- ]?escalation|"
    r"middleware|hidden[- ]?button|hide[- ]?button|happy[- ]?path[- ]?endpoint|"
    r"admin[- ]?role)\b|"
    r"API\s*端点|端点强制|界面入口|后台任务|异步任务|导出|报表|审计日志|"
    r"角色变更|组映射|临时权限|策略版本发布|缓存失效|缓存陈旧|撤销|吊销|"
    r"负向授权|跨资源提权|只隐藏按钮|隐藏按钮|只加中间件|中间件|只检查管理员|"
    r"只检查\s*admin|happy\s*path\s*端点).{0,320}"
    r"(?:\b(?:authorization[- ]?policy|policy[- ]?(?:engine|decision|version|evaluation)|"
    r"rbac|abac|role[- ]?hierarchy|resource[- ]?scope|team[- ]?membership|"
    r"owner/admin/viewer|deny[- ]?overrides[- ]?allow|field[- ]?level[- ]?permissions?|"
    r"permission[- ]?matrix|access[- ]?matrix|authorization[- ]?matrix|"
    r"policy[- ]?decision[- ]?trace|pdp|pep|opa|casbin)\b|"
    r"授权策略|权限策略|策略引擎|策略决策|策略版本|策略评估|RBAC|ABAC|"
    r"角色层级|资源范围|团队成员关系|拒绝优先|字段级权限|权限矩阵|访问矩阵|授权矩阵|"
    r"策略决策追踪|策略决策链))"
)


DATA_RESIDENCY_REGIONAL_ISOLATION_PATTERN = (
    r"(?:(?:\b(?:data[- ]?residen(?:cy|ce)|regional[- ]?isolation|region[- ]?isolation|"
    r"tenant[- ]?residency|residency[- ]?policy|data[- ]?region|region[- ]?routing|"
    r"region[- ]?policy|data[- ]?location|data[- ]?boundary|wrong[- ]?region|"
    r"(?:eu|us|uk|apac)\s+(?:tenant|region))\b|数据驻留|区域隔离|地区隔离|租户驻留|"
    r"驻留策略|数据区域|区域路由|区域策略|数据边界|错误区域|错区).{0,360}"
    r"(?:\b(?:primary[- ]?(?:db|database)|object[- ]?storage|blob[- ]?storage|"
    r"search[- ]?index|cache|queue|backup(?:s)?|logs?|analytics[- ]?export|"
    r"third[- ]?party[- ]?processor|processor(?:s)?|subprocessor(?:s)?|"
    r"subprocessor[- ]?allowlist|dpa|encryption[- ]?key[- ]?region|key[- ]?region|"
    r"cross[- ]?region[- ]?failover|migration|backfill|support[- ]?access|"
    r"admin[- ]?access|data[- ]?export|audit[- ]?log|observability[- ]?trace|"
    r"cross[- ]?region[- ]?egress|wrong[- ]?region[- ]?write|"
    r"stale[- ]?residency[- ]?policy|processor[- ]?mismatch)\b|主库|主数据库|对象存储|"
    r"搜索索引|缓存|队列|备份|日志|分析导出|第三方处理方|处理方|子处理方|"
    r"处理方名单|DPA|加密密钥区域|密钥区域|跨区故障转移|跨区域故障转移|迁移|回填|"
    r"客服访问|管理员访问|数据导出|审计日志|观测追踪|跨区出站|跨区域出站|错区写入|"
    r"错误区域写入|驻留策略陈旧|处理方不匹配)"
    r"|(?:\b(?:primary[- ]?(?:db|database)|object[- ]?storage|blob[- ]?storage|"
    r"search[- ]?index|cache|queue|backup(?:s)?|logs?|analytics[- ]?export|"
    r"third[- ]?party[- ]?processor|processor(?:s)?|subprocessor(?:s)?|"
    r"subprocessor[- ]?allowlist|dpa|encryption[- ]?key[- ]?region|key[- ]?region|"
    r"cross[- ]?region[- ]?failover|migration|backfill|support[- ]?access|"
    r"admin[- ]?access|data[- ]?export|audit[- ]?log|observability[- ]?trace|"
    r"cross[- ]?region[- ]?egress|wrong[- ]?region[- ]?write|"
    r"stale[- ]?residency[- ]?policy|processor[- ]?mismatch)\b|主库|主数据库|对象存储|"
    r"搜索索引|缓存|队列|备份|日志|分析导出|第三方处理方|处理方|子处理方|"
    r"处理方名单|DPA|加密密钥区域|密钥区域|跨区故障转移|跨区域故障转移|迁移|回填|"
    r"客服访问|管理员访问|数据导出|审计日志|观测追踪|跨区出站|跨区域出站|错区写入|"
    r"错误区域写入|驻留策略陈旧|处理方不匹配).{0,360}"
    r"(?:\b(?:data[- ]?residen(?:cy|ce)|regional[- ]?isolation|region[- ]?isolation|"
    r"tenant[- ]?residency|residency[- ]?policy|data[- ]?region|region[- ]?routing|"
    r"region[- ]?policy|data[- ]?location|data[- ]?boundary|wrong[- ]?region|"
    r"(?:eu|us|uk|apac)\s+(?:tenant|region))\b|数据驻留|区域隔离|地区隔离|租户驻留|"
    r"驻留策略|数据区域|区域路由|区域策略|数据边界|错误区域|错区))"
)


SUPPORT_IMPERSONATION_BREAKGLASS_PATTERN = (
    r"(?:(?:\b(?:support[- ]?impersonation|user[- ]?impersonation|customer[- ]?impersonation|"
    r"admin[- ]?impersonation|impersonat(?:e|ed|ing|ion)|login[- ]?as|act(?:ing)?[- ]?as|"
    r"on[-_ ]?behalf[-_ ]?of|sudo[- ]?mode|break[- ]?glass(?:[- ]?access)?|"
    r"emergency[- ]?access)\b|"
    r"代理登录|代登录|冒充登录|模拟用户|代客操作|客服代入|管理员代入|"
    r"紧急访问|破窗访问).{0,300}"
    r"(?:\b(?:approved[- ]?ticket|ticket[- ]?approval|customer[- ]?consent|reason[- ]?code|approval|"
    r"supervisor[- ]?approval|time[- ]?bound|limited[- ]?duration|ttl|expires?|expiry|"
    r"session[- ]?attribution|acting[-_ ]?as|on[-_ ]?behalf[-_ ]?of|"
    r"mfa|step[- ]?up(?:[- ]?approval)?|pii[- ]?mask(?:ing)?|"
    r"sensitive[- ]?data[- ]?view|destructive[- ]?action|tenant[- ]?isolation|audit[- ]?log|"
    r"tamper[- ]?evident|immutable|revoke|revoked|revocation|viewed[- ]?records?|change[- ]?records?|"
    r"export[- ]?attempt(?:s)?|download[- ]?attempt(?:s)?|no[- ]?ticket[- ]?impersonation|"
    r"after[- ]?hours[- ]?access|bulk[- ]?record[- ]?view|long[- ]?running[- ]?session)\b|"
    r"审批工单|工单审批|客户同意|原因码|主管审批|限时|时限|有效期|过期|"
    r"会话归因|真实操作者|代理身份|代表用户|目标用户|MFA|二次审批|升级审批|"
    r"共享管理员令牌|共享管理员token|PII\s*遮蔽|敏感数据查看|破坏性操作|租户隔离|"
    r"审计日志|不可篡改|防篡改|撤销|吊销|查看记录|变更记录|导出尝试|下载尝试|"
    r"无工单代理|非工单代理|下班访问|批量查看|长会话)"
    r"|(?:\b(?:approved[- ]?ticket|ticket[- ]?approval|customer[- ]?consent|reason[- ]?code|approval|"
    r"supervisor[- ]?approval|time[- ]?bound|limited[- ]?duration|ttl|expires?|expiry|"
    r"session[- ]?attribution|acting[-_ ]?as|on[-_ ]?behalf[-_ ]?of|"
    r"mfa|step[- ]?up(?:[- ]?approval)?|pii[- ]?mask(?:ing)?|"
    r"sensitive[- ]?data[- ]?view|destructive[- ]?action|tenant[- ]?isolation|audit[- ]?log|"
    r"tamper[- ]?evident|immutable|revoke|revoked|revocation|viewed[- ]?records?|change[- ]?records?|"
    r"export[- ]?attempt(?:s)?|download[- ]?attempt(?:s)?|no[- ]?ticket[- ]?impersonation|"
    r"after[- ]?hours[- ]?access|bulk[- ]?record[- ]?view|long[- ]?running[- ]?session)\b|"
    r"审批工单|工单审批|客户同意|原因码|主管审批|限时|时限|有效期|过期|"
    r"会话归因|真实操作者|代理身份|代表用户|目标用户|MFA|二次审批|升级审批|"
    r"共享管理员令牌|共享管理员token|PII\s*遮蔽|敏感数据查看|破坏性操作|租户隔离|"
    r"审计日志|不可篡改|防篡改|撤销|吊销|查看记录|变更记录|导出尝试|下载尝试|"
    r"无工单代理|非工单代理|下班访问|批量查看|长会话).{0,300}"
    r"(?:\b(?:support[- ]?impersonation|user[- ]?impersonation|customer[- ]?impersonation|"
    r"admin[- ]?impersonation|impersonat(?:e|ed|ing|ion)|login[- ]?as|act(?:ing)?[- ]?as|"
    r"on[-_ ]?behalf[-_ ]?of|sudo[- ]?mode|break[- ]?glass(?:[- ]?access)?|"
    r"emergency[- ]?access|support[- ]?access|admin[- ]?access)\b|"
    r"代理登录|代登录|冒充登录|模拟用户|代客操作|客服代入|客服访问|管理员代入|"
    r"管理员访问|紧急访问|破窗访问))"
)


__all__ = (
    "AUTHORIZATION_POLICY_CONSISTENCY_PATTERN",
    "DATA_RESIDENCY_REGIONAL_ISOLATION_PATTERN",
    "SUPPORT_IMPERSONATION_BREAKGLASS_PATTERN",
    "TENANT_ISOLATION_PATTERN",
)
