from __future__ import annotations

"""Compatibility aggregate for data-family domain-risk patterns."""

from loopora.alignment_traceability_domain_patterns_data_commerce import (
    INVENTORY_RESERVATION_CONSISTENCY_PATTERN,
    SUBSCRIPTION_ENTITLEMENT_BILLING_PATTERN,
    TAX_CALCULATION_COMPLIANCE_PATTERN,
    USAGE_QUOTA_METERING_PATTERN,
)
from loopora.alignment_traceability_domain_patterns_data_ingest import (
    CONCURRENCY_CONFLICT_RESOLUTION_PATTERN,
    DATA_IMPORT_VALIDATION_IDEMPOTENCY_PATTERN,
    FILE_UPLOAD_STORAGE_SAFETY_PATTERN,
)
from loopora.alignment_traceability_domain_patterns_data_lifecycle import (
    CONSENT_PREFERENCE_GOVERNANCE_PATTERN,
    DATA_LIFECYCLE_DELETION_RETENTION_PATTERN,
)
from loopora.alignment_traceability_domain_patterns_data_read_models import (
    CACHE_INVALIDATION_CONSISTENCY_PATTERN,
    SEARCH_INDEX_CONSISTENCY_PATTERN,
)
from loopora.alignment_traceability_domain_patterns_data_resilience import (
    AUDIT_LOG_INTEGRITY_RETENTION_PATTERN,
    BACKUP_RESTORE_RECOVERY_PATTERN,
    CDC_REPLICATION_CONSISTENCY_PATTERN,
)

__all__ = (
    "AUDIT_LOG_INTEGRITY_RETENTION_PATTERN",
    "BACKUP_RESTORE_RECOVERY_PATTERN",
    "CACHE_INVALIDATION_CONSISTENCY_PATTERN",
    "CDC_REPLICATION_CONSISTENCY_PATTERN",
    "CONCURRENCY_CONFLICT_RESOLUTION_PATTERN",
    "CONSENT_PREFERENCE_GOVERNANCE_PATTERN",
    "DATA_IMPORT_VALIDATION_IDEMPOTENCY_PATTERN",
    "DATA_LIFECYCLE_DELETION_RETENTION_PATTERN",
    "FILE_UPLOAD_STORAGE_SAFETY_PATTERN",
    "INVENTORY_RESERVATION_CONSISTENCY_PATTERN",
    "SEARCH_INDEX_CONSISTENCY_PATTERN",
    "SUBSCRIPTION_ENTITLEMENT_BILLING_PATTERN",
    "TAX_CALCULATION_COMPLIANCE_PATTERN",
    "USAGE_QUOTA_METERING_PATTERN",
)
