from __future__ import annotations

"""Evidence-preference category catalog for Agent-candidate traceability."""

from loopora.alignment_traceability_domain_patterns import (
    ACCESSIBILITY_A11Y_PATTERN,
    ANALYTICS_EVENT_INTEGRITY_PATTERN,
    AUDIT_LOG_INTEGRITY_RETENTION_PATTERN,
    ASYNC_JOB_LIFECYCLE_PATTERN,
    AUTH_SESSION_TOKEN_LIFECYCLE_PATTERN,
    AUTHORIZATION_POLICY_CONSISTENCY_PATTERN,
    BACKUP_RESTORE_RECOVERY_PATTERN,
    BACKWARD_COMPATIBILITY_PATTERN,
    BILLING_LEDGER_RECONCILIATION_PATTERN,
    CACHE_INVALIDATION_CONSISTENCY_PATTERN,
    CDC_REPLICATION_CONSISTENCY_PATTERN,
    CONSENT_PREFERENCE_GOVERNANCE_PATTERN,
    CONCURRENCY_CONFLICT_RESOLUTION_PATTERN,
    DATA_IMPORT_VALIDATION_IDEMPOTENCY_PATTERN,
    DATA_LIFECYCLE_DELETION_RETENTION_PATTERN,
    DATA_RESIDENCY_REGIONAL_ISOLATION_PATTERN,
    DISPUTE_CHARGEBACK_LIFECYCLE_PATTERN,
    EVALUATION_SET_PATTERN,
    EXPERIMENT_ASSIGNMENT_CONSISTENCY_PATTERN,
    EXTERNAL_PROVIDER_CONTRACT_PATTERN,
    FEATURE_FLAG_ROLLOUT_SAFETY_PATTERN,
    FILE_UPLOAD_STORAGE_SAFETY_PATTERN,
    HUMAN_REVIEW_QUALITY_PATTERN,
    IDENTITY_PROVISIONING_ROLE_MAPPING_PATTERN,
    IDENTITY_SSO_ASSERTION_PATTERN,
    INCIDENT_ROOT_CAUSE_REPRO_PATTERN,
    INVENTORY_RESERVATION_CONSISTENCY_PATTERN,
    KYC_AML_SANCTIONS_SCREENING_PATTERN,
    KEY_ROTATION_SECRET_LIFECYCLE_PATTERN,
    LOCALE_I18N_PATTERN,
    METRIC_REPORTING_RECONCILIATION_PATTERN,
    MIGRATION_ROLLBACK_INTEGRITY_PATTERN,
    NOTIFICATION_SUBSCRIPTION_DELIVERABILITY_PATTERN,
    PAYOUT_SETTLEMENT_RECONCILIATION_PATTERN,
    QUEUE_FAILURE_RECOVERY_PATTERN,
    RAG_GROUNDING_TOOL_SAFETY_PATTERN,
    REGRESSION_MONITORING_GUARD_PATTERN,
    RESILIENCE_RETRY_TIMEOUT_PATTERN,
    SCHEDULE_TIMEZONE_RECURRENCE_PATTERN,
    SEARCH_INDEX_CONSISTENCY_PATTERN,
    SUBSCRIPTION_ENTITLEMENT_BILLING_PATTERN,
    SUPPORT_IMPERSONATION_BREAKGLASS_PATTERN,
    TAX_CALCULATION_COMPLIANCE_PATTERN,
    TENANT_ISOLATION_PATTERN,
    USAGE_QUOTA_METERING_PATTERN,
    WEBHOOK_SIGNATURE_REPLAY_ORDERING_PATTERN,
)


EVIDENCE_PREFERENCE_CATEGORY_PATTERNS = (
    (
        "browser/journey",
        r"\b(?:browser|playwright|journey|end[- ]?to[- ]?end|e2e)\b|浏览器|旅程|端到端",
    ),
    (
        "command/test",
        r"\b(?:command|cli|script|test|tests|pytest|unit|contract|lint|typecheck)\b|命令|脚本|测试|契约|类型检查",
    ),
    (
        "audit/log",
        r"\b(?:audit|auditing|audit[- ]?log|log|logs|ledger|trace)\b|审计|日志|账本|追踪",
    ),
    (
        "permission/auth",
        r"\b(?:permission|permissions|authorization|auth|access|acl|access[- ]?control|permission[- ]?filter(?:ing)?|access[- ]?filter(?:ing)?)\b|权限|授权|访问|ACL|权限过滤|访问控制",
    ),
    ("access/authorization-policy-consistency", AUTHORIZATION_POLICY_CONSISTENCY_PATTERN),
    ("payment/refund/billing", r"\b(?:payment|payments|refund|refunds|billing|invoice|checkout)\b|支付|退款|账单|发票|结账"),
    ("data/export/report", r"\b(?:data|export|download|csv|report|dashboard)\b|数据|导出|下载|报表|看板"),
    ("migration/rollback-integrity", MIGRATION_ROLLBACK_INTEGRITY_PATTERN),
    ("compatibility/backward-compat", BACKWARD_COMPATIBILITY_PATTERN),
    ("evaluation/eval-set", EVALUATION_SET_PATTERN),
    ("quality/human-review", HUMAN_REVIEW_QUALITY_PATTERN),
    ("ai/rag-grounding-tool-safety", RAG_GROUNDING_TOOL_SAFETY_PATTERN),
    ("incident/root-cause-repro", INCIDENT_ROOT_CAUSE_REPRO_PATTERN),
    ("regression/monitoring-guard", REGRESSION_MONITORING_GUARD_PATTERN),
    ("release/feature-flag-rollout", FEATURE_FLAG_ROLLOUT_SAFETY_PATTERN),
    ("external/provider-contract", EXTERNAL_PROVIDER_CONTRACT_PATTERN),
    ("compliance/kyc-aml-sanctions-screening", KYC_AML_SANCTIONS_SCREENING_PATTERN),
    ("resilience/retry-timeout", RESILIENCE_RETRY_TIMEOUT_PATTERN),
    ("access/tenant-isolation", TENANT_ISOLATION_PATTERN),
    ("data/residency-regional-isolation", DATA_RESIDENCY_REGIONAL_ISOLATION_PATTERN),
    ("access/support-impersonation-breakglass", SUPPORT_IMPERSONATION_BREAKGLASS_PATTERN),
    ("file-upload/storage-safety", FILE_UPLOAD_STORAGE_SAFETY_PATTERN),
    ("data-import/validation-idempotency", DATA_IMPORT_VALIDATION_IDEMPOTENCY_PATTERN),
    ("concurrency/conflict-resolution", CONCURRENCY_CONFLICT_RESOLUTION_PATTERN),
    ("inventory/reservation-consistency", INVENTORY_RESERVATION_CONSISTENCY_PATTERN),
    ("usage/quota-metering", USAGE_QUOTA_METERING_PATTERN),
    ("billing/subscription-entitlement-proration", SUBSCRIPTION_ENTITLEMENT_BILLING_PATTERN),
    ("tax/calculation-compliance", TAX_CALCULATION_COMPLIANCE_PATTERN),
    ("backup/restore-recovery", BACKUP_RESTORE_RECOVERY_PATTERN),
    ("data/cdc-replication-consistency", CDC_REPLICATION_CONSISTENCY_PATTERN),
    ("audit/log-integrity-retention", AUDIT_LOG_INTEGRITY_RETENTION_PATTERN),
    ("cache/invalidation-consistency", CACHE_INVALIDATION_CONSISTENCY_PATTERN),
    ("search/index-consistency", SEARCH_INDEX_CONSISTENCY_PATTERN),
    ("data-lifecycle/deletion-retention", DATA_LIFECYCLE_DELETION_RETENTION_PATTERN),
    ("privacy/consent-preference-governance", CONSENT_PREFERENCE_GOVERNANCE_PATTERN),
    ("analytics/event-integrity", ANALYTICS_EVENT_INTEGRITY_PATTERN),
    ("experiment/assignment-consistency", EXPERIMENT_ASSIGNMENT_CONSISTENCY_PATTERN),
    ("async/job-lifecycle", ASYNC_JOB_LIFECYCLE_PATTERN),
    ("queue/failure-recovery", QUEUE_FAILURE_RECOVERY_PATTERN),
    ("schedule/timezone-recurrence", SCHEDULE_TIMEZONE_RECURRENCE_PATTERN),
    ("webhook/signature-replay-ordering", WEBHOOK_SIGNATURE_REPLAY_ORDERING_PATTERN),
    ("billing/ledger-reconciliation", BILLING_LEDGER_RECONCILIATION_PATTERN),
    ("payment/dispute-chargeback-lifecycle", DISPUTE_CHARGEBACK_LIFECYCLE_PATTERN),
    ("payout/settlement-reconciliation", PAYOUT_SETTLEMENT_RECONCILIATION_PATTERN),
    ("reporting/metric-reconciliation", METRIC_REPORTING_RECONCILIATION_PATTERN),
    ("identity/sso-assertion", IDENTITY_SSO_ASSERTION_PATTERN),
    ("identity/provisioning-role-mapping", IDENTITY_PROVISIONING_ROLE_MAPPING_PATTERN),
    ("auth/session-token-lifecycle", AUTH_SESSION_TOKEN_LIFECYCLE_PATTERN),
    ("security/key-rotation-lifecycle", KEY_ROTATION_SECRET_LIFECYCLE_PATTERN),
    ("notification/subscription-deliverability", NOTIFICATION_SUBSCRIPTION_DELIVERABILITY_PATTERN),
    ("artifact/ref", r"\b(?:artifact|artifacts|file|files|ref|refs|report)\b|产物|文件|引用|报告"),
    (
        "idempotency/duplicate-prevention",
        r"\b(?:duplicate|duplicated|dedupe|deduplicat(?:e|ed|ion)|idempotent|idempotency|exactly\s+once|only\s+once)\b|重复|去重|幂等|只发一次|仅发一次",
    ),
    (
        "privacy/secrets-redaction",
        r"\b(?:privacy|private|pii|personal\s+data|sensitive\s+data|secret|secrets|token|tokens|password|credential|credentials|redact|redacted|redaction|mask|masked|leak|leakage|plain[- ]?text)\b|隐私|个人信息|敏感数据|敏感信息|密钥|令牌|口令|密码|凭据|脱敏|掩码|泄露|明文|手机号|身份证",
    ),
    ("accessibility/a11y", ACCESSIBILITY_A11Y_PATTERN),
    ("locale/i18n", LOCALE_I18N_PATTERN),
    ("screenshot-is-weak", r"\b(?:screenshot|screenshots)\b|截图"),
)
