from __future__ import annotations

import logging
from pathlib import Path
from typing import Annotated

import typer
import uvicorn

from loopora.agent_adapter_command_prefix import rewrite_loopora_help_commands
from loopora.branding import APP_AUTH_ENV
from loopora.cli_shared import handle_error, logger
from loopora.cli_serve_language import serve_text
from loopora.cli_serve_command_projection import copyable_serve_start_command as copyable_serve_start_command
from loopora.cli_serve_command_projection import serve_alternate_port_action as serve_alternate_port_action
from loopora.cli_serve_command_projection import (
    serve_development_reset_extra_recovery_lines as serve_development_reset_extra_recovery_lines,
)
from loopora.cli_serve_command_projection import serve_retry_command as serve_retry_command
from loopora.cli_serve_command_projection import serve_start_command as serve_start_command
from loopora.cli_serve_command_projection import serve_temporary_app_home_action as serve_temporary_app_home_action
from loopora.cli_serve_command_projection import (
    serve_temporary_app_home_command as serve_temporary_app_home_command,
)
from loopora.diagnostics import log_event
from loopora.first_use_web_guidance import WEB_CREATION_CHOICE_SUMMARY
from loopora.fit_guidance import normalize_fit_guidance_language
from loopora.service import LooporaError
from loopora.serve_browser_open import open_browser_now, schedule_browser_open_if_requested
from loopora.settings import app_home
from loopora.service_types import LooporaWorkdirUnavailableError
from loopora.web import build_app
from loopora.web_origins import open_origin_for_bind_host
from loopora.web_request_context import _is_loopback_host
from loopora.web_service_probe import loopora_web_responds

AllowUnsafeOpenOption = Annotated[
    bool,
    typer.Option(
        "--allow-unsafe-open",
        help="Allow non-loopback hosts without an auth token. Dangerous on shared networks.",
    ),
]
ServeWorkdirOption = Annotated[
    Path | None,
    typer.Option(
        "--workdir",
        file_okay=True,
        dir_okay=True,
        exists=False,
        help="Project directory to preselect when Web opens.",
    ),
]
ServeJsonOutputOption = Annotated[
    bool,
    typer.Option("--json", help="Print structured JSON for startup validation or recovery failures instead of plain text."),
]
ServeOpenOption = Annotated[
    bool,
    typer.Option(
        "--open",
        help="Open the selected local Web page. Starts foreground Web when needed; reuses a matching instance and exits.",
    ),
]
ServeLanguageOption = Annotated[
    str,
    typer.Option(
        "--language",
        help="Plain Web-start language: en or zh; common aliases like en-US and zh-CN are normalized.",
    ),
]
ServeOpenPathOption = Annotated[
    str,
    typer.Option(
        "--open-path",
        hidden=True,
        help="Relative local Web path opened by --open; generated by first-use route commands.",
    ),
]


def register_serve_command(app: typer.Typer) -> None:  # noqa: C901 - registration owns the complete startup gate.
    from loopora.cli_serve_output import (
        exit_if_serve_app_state_not_ready,
        exit_if_serve_bind_unavailable,
        exit_with_serve_startup_recovery,
        exit_with_serve_workdir_recovery,
        normalize_auth_token,
        normalize_serve_port_or_exit,
        print_serve_existing_web_summary,
        print_serve_startup_summary,
        serve_app_state_report,
        serve_network_auth_recovery_payload,
        serve_browser_url_or_exit,
        serve_startup_workdir,
    )

    @app.command(epilog=rewrite_loopora_help_commands(SERVE_HELP_EPILOG))
    def serve(  # noqa: C901, PLR0913 - Public CLI startup options mirror the serve safety contract.
        host: str = typer.Option("127.0.0.1", help="Bind host."),
        port: str = typer.Option("8742", help="Bind port."),
        auth_token: str = typer.Option(
            "",
            "--auth-token",
            envvar=APP_AUTH_ENV,
            help="Optional token required for all web and API requests.",
        ),
        workdir: ServeWorkdirOption = None,
        *,
        language: ServeLanguageOption = "en",
        json_output: ServeJsonOutputOption = False,
        allow_unsafe_open: AllowUnsafeOpenOption = False,
        open_browser: ServeOpenOption = False,
        open_path: ServeOpenPathOption = "",
    ) -> None:
        """Run the local Web UI."""
        try:
            language = normalize_fit_guidance_language(language)
        except ValueError as exc:
            if json_output:
                handle_error(ValueError(f"invalid --language: {exc}"), json_output=True, recovery_workdir=workdir)
                return
            typer.echo(f"invalid --language: {exc}", err=True)
            raise typer.Exit(code=2) from exc
        normalized_port = normalize_serve_port_or_exit(port, json_output=json_output, language=language)
        normalized_auth_token = normalize_auth_token(auth_token)
        try:
            startup_workdir = serve_startup_workdir(workdir)
        except LooporaWorkdirUnavailableError:
            exit_with_serve_workdir_recovery(
                workdir=workdir,
                host=host,
                port=normalized_port,
                allow_unsafe_open=allow_unsafe_open,
                auth_token_configured=bool(normalized_auth_token),
                language=language,
                json_output=json_output,
            )
        browser_url = serve_browser_url_or_exit(
            open_browser=open_browser,
            open_path=open_path,
            host=host,
            port=normalized_port,
            startup_workdir=startup_workdir,
            language=language,
        )
        app_state = serve_app_state_report(startup_workdir)
        if not _is_loopback_host(host) and not normalized_auth_token and not allow_unsafe_open:
            exit_with_serve_startup_recovery(
                serve_network_auth_recovery_payload(
                    host=host,
                    port=normalized_port,
                    startup_workdir=startup_workdir,
                    app_state=app_state,
                ),
                language=language,
                json_output=json_output,
            )
        if open_browser and loopora_web_responds(
            open_origin_for_bind_host(host, normalized_port),
            expected_app_home=str(app_home().resolve()),
            auth_token=normalized_auth_token,
        ):
            log_event(
                logger,
                logging.INFO,
                "cli.server.reused",
                "Reusing the existing local web console",
                bind_host=host,
                bind_port=normalized_port,
                auth_enabled=bool(normalized_auth_token),
                startup_workdir=startup_workdir,
            )
            print_serve_existing_web_summary(
                host=host,
                port=normalized_port,
                auth_token=normalized_auth_token,
                startup_workdir=startup_workdir,
                browser_url=browser_url,
                language=language,
            )
            open_browser_now(browser_url)
            return
        log_event(
            logger,
            logging.INFO,
            "cli.server.starting",
            "Starting the local web console",
            bind_host=host,
            bind_port=normalized_port,
            auth_enabled=bool(normalized_auth_token),
            allow_unsafe_open=allow_unsafe_open,
            startup_workdir=startup_workdir,
        )
        exit_if_serve_bind_unavailable(
            host=host,
            port=normalized_port,
            startup_workdir=startup_workdir,
            allow_unsafe_open=allow_unsafe_open,
            auth_token_configured=bool(normalized_auth_token),
            app_state=app_state,
            language=language,
            json_output=json_output,
        )
        exit_if_serve_app_state_not_ready(
            host=host,
            port=normalized_port,
            startup_workdir=startup_workdir,
            allow_unsafe_open=allow_unsafe_open,
            auth_token_configured=bool(normalized_auth_token),
            app_state=app_state,
            language=language,
            json_output=json_output,
        )
        if not _is_loopback_host(host):
            typer.secho(
                serve_text(
                    language,
                    "Network mode enabled. Use absolute paths from the server machine in the Web UI; native file dialogs are disabled.",
                    "已启用网络模式。请在 Web UI 中使用服务器机器上的绝对路径；原生文件选择器已禁用。",
                ),
                fg=typer.colors.YELLOW,
            )
            if normalized_auth_token:
                typer.secho(
                    serve_text(
                        language,
                        "Open the UI and submit the token form, or send Authorization: Bearer for automation.",
                        "打开 UI 并提交 token 表单；自动化请求请发送 Authorization: Bearer。",
                    ),
                    fg=typer.colors.YELLOW,
                )
        try:
            build_kwargs = {
                "bind_host": host,
                "bind_port": normalized_port,
                "auth_token": normalized_auth_token or None,
            }
            if startup_workdir:
                build_kwargs["startup_workdir"] = startup_workdir
            if allow_unsafe_open:
                build_kwargs["allow_unsafe_open"] = True
            web_app = build_app(**build_kwargs)
        except LooporaError as exc:
            handle_error(
                exc,
                json_output=json_output,
                recovery_workdir=Path.cwd(),
                extra_recovery_lines=serve_development_reset_extra_recovery_lines(
                    host=host,
                    port=normalized_port,
                    startup_workdir=startup_workdir,
                    allow_unsafe_open=allow_unsafe_open,
                    auth_token_configured=bool(normalized_auth_token),
                    language=language,
                ),
            )
        print_serve_startup_summary(
            host=host,
            port=normalized_port,
            auth_token=normalized_auth_token,
            startup_workdir=startup_workdir,
            browser_url=browser_url,
            language=language,
        )
        schedule_browser_open_if_requested(browser_url)
        uvicorn.run(
            web_app,
            host=host,
            port=normalized_port,
            log_level="info",
            access_log=False,
        )


SERVE_HELP_EPILOG = (
    "Default use is local-only: run "
    f'`loopora serve --open --workdir "$PWD" --host 127.0.0.1 --port 8742` to start Web, open it in the default browser, and use it as the Fit Guide and Web choices entry for {WEB_CREATION_CHOICE_SUMMARY}. '
    "For a new service, keep that command running and use Ctrl-C to stop it. If the same App home already owns a responding service at that origin, --open reuses it and exits after opening; its original terminal still owns shutdown. "
    "After Web opens, start from Fit Guide when fit is uncertain; then choose from creation choices: Web conversation is the browser-first planning path, "
    "same-Agent setup prepares the handoff back to your current Codex, Claude Code, or OpenCode host, "
    "import/manual expert paths are for existing reviewed plan files or exact contracts, "
    "and existing-work views focus on evidence, verdict state, residual risk, and next action. "
    'Use `loopora doctor --workdir "$PWD"` when preparing the same-Agent path or checking a custom Web host/port. '
    "For network access, keep an auth token configured with --auth-token or LOOPORA_AUTH_TOKEN; "
    "--allow-unsafe-open is an explicit unsafe opt-in."
)
