from __future__ import annotations

from loopora.context_schema_evidence import (
    ARTIFACT_REF_SCHEMA,
    EVIDENCE_COVERAGE_GAP_SCHEMA,
    EVIDENCE_ITEM_SCHEMA,
    EVIDENCE_MANIFEST_CLAIM_SCHEMA,
    EVIDENCE_MANIFEST_SUMMARY_SCHEMA,
)
from loopora.context_schema_shared import (
    CONTINUATION_CONTEXT_SCHEMA,
    ROLE_POSTURE_CONTRACT_SCHEMA,
    STEP_HANDOFF_SCHEMA,
)

STEP_INSTRUCTION_CONTEXT_SCHEMA = {
    "type": "object",
    "required": ["contract", "continuation", "iteration", "current_step", "upstream", "evidence", "artifacts"],
    "properties": {
        "contract": {
            "type": "object",
            "required": [
                "path",
                "goal",
                "constraints",
                "check_mode",
                "check_count",
                "completion_mode",
                "collaboration_summary",
                "loop_fit_reasons",
                "strategy_preset",
                "strategy_collaboration_intent",
                "judgment_tradeoffs",
                "execution_strategy",
                "local_governance",
                "role_postures",
                "coverage_targets",
                "success_surface",
                "fake_done_states",
                "evidence_preferences",
                "residual_risk",
            ],
            "properties": {
                "path": {"type": "string"},
                "goal": {"type": "string"},
                "constraints": {"type": "string"},
                "check_mode": {"type": "string"},
                "check_count": {"type": "integer"},
                "completion_mode": {"type": "string"},
                "collaboration_summary": {"type": "string"},
                "loop_fit_reasons": {"type": "array", "items": {"type": "string"}},
                "strategy_preset": {"type": "string"},
                "strategy_collaboration_intent": {"type": "string"},
                "judgment_tradeoffs": {"type": "array", "items": {"type": "string"}},
                "execution_strategy": {"type": "array", "items": {"type": "string"}},
                "local_governance": {"type": "array", "items": {"type": "string"}},
                "role_postures": {"type": "array", "items": ROLE_POSTURE_CONTRACT_SCHEMA},
                "coverage_targets": {"type": "array", "items": {"type": "object"}},
                "success_surface": {"type": "array", "items": {"type": "string"}},
                "fake_done_states": {"type": "array", "items": {"type": "string"}},
                "evidence_preferences": {"type": "array", "items": {"type": "string"}},
                "residual_risk": {"type": "string"},
            },
            "additionalProperties": False,
        },
        "continuation": CONTINUATION_CONTEXT_SCHEMA,
        "iteration": {
            "type": "object",
            "required": [
                "iter_index",
                "is_first_iteration",
                "previous_iteration_exists",
                "previous_composite",
                "stagnation_mode",
                "evidence_progress_mode",
                "coverage_status",
                "covered_check_count",
                "missing_check_count",
                "covered_check_ids",
                "missing_check_ids",
                "target_count",
                "covered_target_count",
                "weak_target_count",
                "missing_target_count",
                "blocked_target_count",
                "coverage_top_gaps",
                "consecutive_no_required_coverage_delta",
            ],
            "properties": {
                "iter_index": {"type": "integer"},
                "is_first_iteration": {"type": "boolean"},
                "previous_iteration_exists": {"type": "boolean"},
                "previous_composite": {"type": ["number", "null"]},
                "stagnation_mode": {"type": "string"},
                "evidence_progress_mode": {"type": "string"},
                "coverage_status": {"type": "string"},
                "covered_check_count": {"type": "integer"},
                "missing_check_count": {"type": "integer"},
                "covered_check_ids": {"type": "array", "items": {"type": "string"}},
                "missing_check_ids": {"type": "array", "items": {"type": "string"}},
                "target_count": {"type": "integer"},
                "covered_target_count": {"type": "integer"},
                "weak_target_count": {"type": "integer"},
                "missing_target_count": {"type": "integer"},
                "blocked_target_count": {"type": "integer"},
                "coverage_top_gaps": {"type": "array", "items": EVIDENCE_COVERAGE_GAP_SCHEMA},
                "consecutive_no_required_coverage_delta": {"type": "integer"},
            },
            "additionalProperties": False,
        },
        "current_step": {
            "type": "object",
            "required": [
                "step_id",
                "step_order",
                "role_id",
                "role_name",
                "archetype",
                "model",
                "executor_kind",
                "executor_mode",
                "parallel_group",
                "inputs",
                "action_policy",
                "control",
            ],
            "properties": {
                "step_id": {"type": "string"},
                "step_order": {"type": "integer"},
                "role_id": {"type": "string"},
                "role_name": {"type": "string"},
                "archetype": {"type": "string"},
                "model": {"type": "string"},
                "executor_kind": {"type": "string"},
                "executor_mode": {"type": "string"},
                "parallel_group": {"type": "string"},
                "inputs": {"type": "object"},
                "action_policy": {
                    "type": "object",
                    "required": ["workspace", "can_block", "can_finish_run"],
                    "properties": {
                        "workspace": {"type": "string"},
                        "can_block": {"type": "boolean"},
                        "can_finish_run": {"type": "boolean"},
                    },
                    "additionalProperties": False,
                },
                "control": {"type": "object"},
            },
            "additionalProperties": False,
        },
        "upstream": {
            "type": "object",
            "required": [
                "immediate_previous_step",
                "completed_steps_this_iteration",
                "previous_iteration_same_step",
                "previous_iteration_same_role",
                "previous_iteration_summary",
            ],
            "properties": {
                "immediate_previous_step": {"anyOf": [STEP_HANDOFF_SCHEMA, {"type": "null"}]},
                "completed_steps_this_iteration": {"type": "array", "items": STEP_HANDOFF_SCHEMA},
                "previous_iteration_same_step": {"anyOf": [STEP_HANDOFF_SCHEMA, {"type": "null"}]},
                "previous_iteration_same_role": {"anyOf": [STEP_HANDOFF_SCHEMA, {"type": "null"}]},
                "previous_iteration_summary": {"type": ["object", "null"]},
            },
            "additionalProperties": False,
        },
        "evidence": {
            "type": "object",
            "required": [
                "ledger_path",
                "manifest_path",
                "coverage_path",
                "items",
                "known_ids",
                "manifest_summary",
                "manifest_claims",
            ],
            "properties": {
                "ledger_path": {"type": "string"},
                "manifest_path": {"type": "string"},
                "coverage_path": {"type": "string"},
                "items": {"type": "array", "items": EVIDENCE_ITEM_SCHEMA},
                "known_ids": {"type": "array", "items": {"type": "string"}},
                "manifest_summary": EVIDENCE_MANIFEST_SUMMARY_SCHEMA,
                "manifest_claims": {"type": "array", "items": EVIDENCE_MANIFEST_CLAIM_SCHEMA},
            },
            "additionalProperties": False,
        },
        "artifacts": {"type": "array", "items": ARTIFACT_REF_SCHEMA},
    },
    "additionalProperties": False,
}
