from __future__ import annotations

from loopora import executor_alignment_task_predicates as _task_predicates

_agreement_is_rag_long_chain_task = _task_predicates.is_rag_long_chain_task
_agreement_is_schedule_phase_task = _task_predicates.is_schedule_phase_task
_agreement_is_prompt_asset_ownership_task = _task_predicates.is_prompt_asset_ownership_task
_agreement_is_backup_restore_recovery_task = _task_predicates.is_backup_restore_recovery_task
_agreement_is_audit_log_integrity_retention_task = _task_predicates.is_audit_log_integrity_retention_task
_agreement_is_analytics_experiment_instrumentation_task = _task_predicates.is_analytics_experiment_instrumentation_task
_agreement_is_database_schema_migration_task = _task_predicates.is_database_schema_migration_task
_agreement_is_cdc_replication_consistency_task = _task_predicates.is_cdc_replication_consistency_task
_agreement_is_metric_reporting_reconciliation_task = _task_predicates.is_metric_reporting_reconciliation_task
_agreement_is_dispute_chargeback_lifecycle_task = _task_predicates.is_dispute_chargeback_lifecycle_task
_agreement_is_payout_settlement_reconciliation_task = _task_predicates.is_payout_settlement_reconciliation_task
_agreement_is_support_ticket_sla_task = _task_predicates.is_support_ticket_sla_task
_agreement_is_dsar_data_export_task = _task_predicates.is_dsar_data_export_task
_agreement_is_notification_subscription_deliverability_task = _task_predicates.is_notification_subscription_deliverability_task
_agreement_is_data_lifecycle_deletion_retention_task = _task_predicates.is_data_lifecycle_deletion_retention_task
_agreement_is_feature_flag_rollout_task = _task_predicates.is_feature_flag_rollout_task
_agreement_is_cache_invalidation_consistency_task = _task_predicates.is_cache_invalidation_consistency_task
_agreement_is_data_import_validation_task = _task_predicates.is_data_import_validation_task
_agreement_is_concurrency_conflict_resolution_task = _task_predicates.is_concurrency_conflict_resolution_task
_agreement_is_usage_quota_metering_task = _task_predicates.is_usage_quota_metering_task
_agreement_is_subscription_entitlement_billing_task = _task_predicates.is_subscription_entitlement_billing_task
_agreement_is_tax_calculation_compliance_task = _task_predicates.is_tax_calculation_compliance_task
_agreement_is_inventory_reservation_consistency_task = _task_predicates.is_inventory_reservation_consistency_task
_agreement_is_file_upload_storage_safety_task = _task_predicates.is_file_upload_storage_safety_task
_agreement_is_auth_session_token_lifecycle_task = _task_predicates.is_auth_session_token_lifecycle_task
_agreement_is_support_impersonation_task = _task_predicates.is_support_impersonation_task
_agreement_is_data_residency_task = _task_predicates.is_data_residency_task
_agreement_is_kyc_aml_screening_task = _task_predicates.is_kyc_aml_screening_task
_agreement_is_identity_sso_task = _task_predicates.is_identity_sso_task
_agreement_is_key_rotation_task = _task_predicates.is_key_rotation_task
_agreement_is_payment_webhook_ledger_task = _task_predicates.is_payment_webhook_ledger_task
_agreement_is_authorization_policy_task = _task_predicates.is_authorization_policy_task
_agreement_is_incident_root_cause_task = _task_predicates.is_incident_root_cause_task
_agreement_is_search_index_consistency_task = _task_predicates.is_search_index_consistency_task
_agreement_is_search_quality_task = _task_predicates.is_search_quality_task
