from __future__ import annotations

from loopora.executor_alignment_agreement_task_responses_trust_access import (
    alignment_english_auth_session_token_lifecycle_agreement_response as alignment_english_auth_session_token_lifecycle_agreement_response,
    alignment_chinese_auth_session_token_lifecycle_agreement_response as alignment_chinese_auth_session_token_lifecycle_agreement_response,
    alignment_spanish_auth_session_token_lifecycle_agreement_response as alignment_spanish_auth_session_token_lifecycle_agreement_response,
    alignment_english_support_impersonation_agreement_response as alignment_english_support_impersonation_agreement_response,
    alignment_chinese_support_impersonation_agreement_response as alignment_chinese_support_impersonation_agreement_response,
    alignment_spanish_support_impersonation_agreement_response as alignment_spanish_support_impersonation_agreement_response,
    alignment_english_identity_sso_agreement_response as alignment_english_identity_sso_agreement_response,
    alignment_chinese_identity_sso_agreement_response as alignment_chinese_identity_sso_agreement_response,
    alignment_spanish_identity_sso_agreement_response as alignment_spanish_identity_sso_agreement_response,
    alignment_english_authorization_policy_agreement_response as alignment_english_authorization_policy_agreement_response,
    alignment_chinese_authorization_policy_agreement_response as alignment_chinese_authorization_policy_agreement_response,
    alignment_spanish_authorization_policy_agreement_response as alignment_spanish_authorization_policy_agreement_response,
)
from loopora.executor_alignment_agreement_task_responses_trust_governance import (
    alignment_english_data_residency_agreement_response as alignment_english_data_residency_agreement_response,
    alignment_chinese_data_residency_agreement_response as alignment_chinese_data_residency_agreement_response,
    alignment_spanish_data_residency_agreement_response as alignment_spanish_data_residency_agreement_response,
    alignment_english_kyc_aml_screening_agreement_response as alignment_english_kyc_aml_screening_agreement_response,
    alignment_chinese_kyc_aml_screening_agreement_response as alignment_chinese_kyc_aml_screening_agreement_response,
    alignment_spanish_kyc_aml_screening_agreement_response as alignment_spanish_kyc_aml_screening_agreement_response,
)
from loopora.executor_alignment_agreement_task_responses_trust_secrets import (
    alignment_english_key_rotation_agreement_response as alignment_english_key_rotation_agreement_response,
    alignment_chinese_key_rotation_agreement_response as alignment_chinese_key_rotation_agreement_response,
    alignment_spanish_key_rotation_agreement_response as alignment_spanish_key_rotation_agreement_response,
    alignment_english_prompt_asset_ownership_agreement_response as alignment_english_prompt_asset_ownership_agreement_response,
    alignment_chinese_prompt_asset_ownership_agreement_response as alignment_chinese_prompt_asset_ownership_agreement_response,
    alignment_spanish_prompt_asset_ownership_agreement_response as alignment_spanish_prompt_asset_ownership_agreement_response,
)
