from __future__ import annotations

from loopora.bundle_io import bundle_to_yaml, load_bundle_text
from loopora.executor_alignment_bundle_base_fixture import alignment_bundle_yaml
from loopora.executor_alignment_bundle_governance_fixture import (
    alignment_bundle_governance_role_snippet as _local_governance_role_snippet,
    alignment_bundle_governance_sentence as _local_governance_bundle_sentence,
)
from loopora.executor_alignment_bundle_localized_assets import apply_localized_base_bundle_overrides


def alignment_chinese_bundle_yaml(workdir: str) -> str:
    bundle = load_bundle_text(alignment_bundle_yaml(workdir))
    apply_localized_base_bundle_overrides(
        bundle,
        locale="zh",
        context={
            "local_governance_sentence": _local_governance_bundle_sentence(workdir, locale="zh"),
            "builder_governance": _local_governance_role_snippet(workdir, role="builder", locale="zh"),
            "inspector_governance": _local_governance_role_snippet(workdir, role="inspector", locale="zh"),
            "gatekeeper_governance": _local_governance_role_snippet(workdir, role="gatekeeper", locale="zh"),
        },
    )
    return bundle_to_yaml(bundle)


def alignment_chinese_bundle_yaml_with_english_visible_names(workdir: str) -> str:
    bundle = load_bundle_text(alignment_chinese_bundle_yaml(workdir))
    bundle["metadata"]["name"] = "Aligned Starter Bundle"
    bundle["metadata"]["description"] = "Bundle generated by the Web alignment flow."
    bundle["loop"]["name"] = "Aligned Starter Bundle"
    role_names = {
        "builder": "Focused Builder",
        "contract-inspector": "Contract Inspector",
        "evidence-inspector": "Evidence Inspector",
        "gatekeeper": "Conservative GateKeeper",
    }
    for role in bundle.get("role_definitions", []):
        if isinstance(role, dict) and str(role.get("key") or "") in role_names:
            role["name"] = role_names[str(role.get("key") or "")]
    return bundle_to_yaml(bundle)
