from __future__ import annotations

import re

from loopora.executor_alignment_bundle_base_fixture import alignment_bundle_yaml
from loopora.executor_alignment_bundle_governance_fixture import (
    alignment_bundle_governance_role_snippet as _local_governance_role_snippet,
    alignment_bundle_governance_sentence as _local_governance_bundle_sentence,
)


def alignment_chinese_bundle_yaml(workdir: str) -> str:
    yaml_text = alignment_bundle_yaml(workdir)
    replacements = {
        '  name: "Aligned Starter Bundle"': '  name: "对齐 Starter Bundle"',
        '  description: "Bundle generated by the Web alignment flow."': ('  description: "由 Web alignment flow 生成的 bundle。"'),
        (
            "  Project the working agreement into a spec task contract for the focused starter slice, role handoffs from Builder / Inspectors / GateKeeper, and a workflow that routes evidence before final judgment. Future iterations stay anchored to this contract as new evidence, blockers, and handoffs appear, rather than treating one Agent pass or one review as enough. Prefer a smaller proven flow over polished but unproven breadth, and let GateKeeper reject speed or surface completeness when evidence is weak. Intermediate control points measure weak evidence and fake-done drift, trigger inspect / correct / halt decisions, and keep the required evidence target explicit. GateKeeper closes only when the spec, role evidence, and workflow handoffs prove the task is truly done. Evidence projection must distinguish Proven direct run proof, Weak indirect evidence, Unproven promised surfaces, Blocking fake-done findings, and visible Residual risk.\n"
        ): (
            "  将工作协议投影到 spec 任务契约、Builder / Inspector / GateKeeper 角色交接，以及先汇集证据再裁决的 workflow。后续轮次会随着新证据、阻断项和 handoff 回到这份契约，而不是把一次 Agent 执行或一次 review 当成足够。优先选择小而已证明的主流程，而不是打磨充分但未证明的宽泛功能；证据薄弱时让 GateKeeper 拒绝速度或表面完整性。中间控制点要测量弱证据和假完成偏差，触发检查、纠正或暂停决策，并让所需证据目标保持明确。GateKeeper 只有在任务契约、角色证据和 workflow handoff 都证明真实完成时才收束。证据投影必须区分已证明的直接运行证据、弱证据、未证明的承诺面、阻断类假完成，以及可见残余风险。\n"
        ),
        ("    Ship the focused starter experience in the target workdir with small, maintainable changes that preserve the primary user flow."): (
            "    在目标 workdir 中交付聚焦的 starter experience，用小而可维护的改动保住主流程，并留下能让 Inspector 和 GateKeeper 验证真实完成的证据路径。"
        ),
        "    - The primary user flow works end to end.": "    - 主流程可以端到端运行。",
        "    - The implementation is covered by project-owned evidence.": "    - 实现有项目内证据覆盖。",
        "    - Keep changes scoped to the requested behavior.": "    - 改动保持在本次请求边界内。",
        (
            "    - The primary user flow is understandable, maintainable, and easy to extend after the first pass."
        ): "    - 主流程可理解、可维护，并且首轮后容易继续扩展。",
        "    - Do not pass with only a happy-path claim and no reproducible evidence.": ("    - 只有 happy path 声称、没有可复现证据时不得通过。"),
        "    - Do not pass if the implementation lacks a handoff that explains what evidence was collected.": (
            "    - 缺少说明已收集证据的 handoff 时不得通过。"
        ),
        "    - Prefer project-owned checks, direct run output, and concrete artifacts before screenshots or claims.": (
            "    - 优先使用项目内检查、直接运行输出和具体产物，而不是截图或口头声称。"
        ),
        "    - Each role should leave a clear handoff note explaining what was changed, inspected, or blocked.": (
            "    - 每个角色都要留下清晰 handoff，说明改了什么、检查了什么或阻断了什么。"
        ),
        "    - Intermediate control points should measure a key risk, trigger a continue / correct / halt decision, and keep the required evidence target explicit.": (
            "    - 中间控制点应测量关键风险，触发继续、纠正或暂停决策，并让所需证据目标保持明确。"
        ),
        "    - Final evidence should be bucketed as Proven, Weak, Unproven, Blocking, or Residual risk instead of flattened into one summary.": (
            "    - 最终证据应区分为已证明、弱证据、未证明、阻断或残余风险，而不是压平成一段总结。"
        ),
        (
            "    Accept minor polish gaps only when they are explicitly named and tracked as an owned follow-up; "
            "fail closed on unproven primary-flow behavior or weak verification evidence."
        ): (
            "    只有明确点名并作为有负责人接手后续事项跟踪的轻微 polish 缺口可以保留；主流程行为未证明或验证证据薄弱时必须 fail closed。"
        ),
        '    name: "Focused Builder"': '    name: "聚焦 Builder"',
        '    name: "Contract Inspector"': '    name: "契约 Inspector"',
        '    name: "Evidence Inspector"': '    name: "证据 Inspector"',
        '    name: "Conservative GateKeeper"': '    name: "审慎 GateKeeper"',
        "    Prefer a small maintainable patch over broad rewrites.": "    优先小而可维护的 patch，不做宽泛重写。",
        "    Collect reproducible evidence and call out missing proof plainly.": ("    收集可复现证据，并直接指出缺失的证明。"),
        "    Fail closed when Done When, fake-done risks, and evidence preferences are not all satisfied.": (
            "    Done When、fake-done 风险和证据偏好没有同时满足时必须 fail closed。"
        ),
        '    description: "Implements the smallest maintainable change."': ('    description: "实现最小且可维护的变更。"'),
        '    description: "Checks the task contract, guardrails, fake-done risks, execution strategy, judgment tradeoffs, local governance, and residual-risk stance."': (
            '    description: "检查任务契约、guardrails、fake-done 风险、执行策略、判断取舍、本地治理和残余风险姿态。"'
        ),
        '    description: "Collects reproducible evidence before sign-off."': ('    description: "在签字前收集可复现证据。"'),
        '    description: "Fails closed when evidence is weak."': '    description: "证据薄弱时 fail closed。"',
        (
            "      Build the focused starter slice carefully and keep the repo coherent. Leave a handoff that names the changed behavior, the verification evidence, and any blocker that should stop Inspector or GateKeeper."
        ): ("      谨慎实现聚焦 starter slice，并保持 repo 一致。留下 handoff，点名变更行为、验证证据，以及应该阻止 Inspector 或 GateKeeper 的 blocker。"),
        ("      Keep implementation narrow and leave the workspace easier to verify; prefer concrete evidence over broad feature spread."): (
            "      保持实现收窄，让 workspace 更容易验证；优先具体证据和清晰 handoff，而不是铺开很多无法证明的功能。"
        ),
        (
            "      Inspect the Builder handoff against Done When, Guardrails, Fake Done, Evidence Preferences, Execution Strategy, Judgment Tradeoffs, Local Governance, and Residual Risk. Your handoff must identify contract mismatches, missing proof, sequencing drift, lowered tradeoffs, local-governance gaps, and any blocker that should prevent GateKeeper from finishing. When evidence is weak, name the decision it should trigger and how the next execution pass should change."
        ): (
            "      根据 Done When、Guardrails、Fake Done、Evidence Preferences、Execution Strategy、Judgment Tradeoffs、Local Governance 和 Residual Risk 检查 Builder handoff。你的 handoff 必须指出契约不匹配、缺失证明、执行顺序漂移、判断取舍被降低、本地治理缺口，以及应阻止 GateKeeper 收束的 blocker。证据薄弱时，要说明应触发什么决策，以及下一轮执行应如何改变。"
        ),
        (
            "      Prefer contract-level proof over broad confidence; block when the delivered slice does not match the agreed scope or leaves fake-done risk unresolved."
        ): ("      优先契约级证明，而不是泛泛信心；交付 slice 不符合约定范围或 fake-done 风险未解决时必须 block。"),
        (
            "      Inspect from direct evidence, project-owned commands, and concrete artifacts. Your handoff must identify the strongest proof, missing proof, and any blocker that should prevent GateKeeper from finishing."
        ): ("      从直接证据、项目内命令和具体产物检查。你的 handoff 必须指出最强证明、缺失证明，以及应阻止 GateKeeper 收束的 blocker。"),
        (
            "      Decide from direct evidence and do not accept vague completion claims. Finish only when the Builder and Inspector handoffs prove the task contract, execution strategy, judgment tradeoffs, local governance when present, and residual-risk stance; otherwise block with the smallest repair. Treat status-only checkpoints as insufficient; the control point must affect correction, closure, or residual-risk handoff."
        ): (
            "      根据直接证据裁决，不接受笼统完成声明。只有 Builder 和 Inspector handoff 证明任务契约、执行策略、判断取舍、存在时的本地治理和残余风险姿态时才收束；否则用最小修复阻断。只记录状态的检查点不够，控制点必须影响纠正、收尾或残余风险交接。"
        ),
        (
            "      Prefer reproducible run output and concrete artifacts; block vague completion claims, screenshots without context, or unverified happy paths."
        ): ("      优先可复现运行输出和具体产物；阻断空泛完成声称、缺上下文截图或未验证 happy path，并说明哪类证据还缺失。"),
        (
            "      Decide from direct evidence and do not accept vague completion claims. Finish only when the Builder and Inspector handoffs prove the task contract; otherwise block with the smallest next repair."
        ): ("      只根据直接证据裁决，不接受空泛完成声称。只有 Builder 和 Inspector handoff 证明任务契约时才 finish；否则用最小下一步修复来 block。"),
        ("      Close only when the task and verification evidence agree; fail closed when handoff evidence is missing or weak."): (
            "      只有任务和验证证据一致时才收束；handoff evidence 缺失、薄弱或没有覆盖主流程时必须 fail closed。"
        ),
        (
            '  collaboration_intent: "Build one focused starter slice, then inspect the contract and evidence in sequence so weak evidence, drift, or fake done surface early, let those control points trigger repair or blocking, then let GateKeeper finish only when both inspection views support the task contract."'
        ): (
            '  collaboration_intent: "先构建一个聚焦 starter slice，然后顺序检查契约和证据，让证据薄弱、偏差或假完成提前暴露，并由这些控制点触发修复或阻断；只有两个检查视角都支持任务契约时，GateKeeper 才能 finish。"'
        ),
    }
    for old, new in replacements.items():
        yaml_text = yaml_text.replace(old, new)
    yaml_text = yaml_text.replace(
        _local_governance_bundle_sentence(workdir, locale="en"),
        _local_governance_bundle_sentence(workdir, locale="zh"),
    )
    for role in ("builder", "inspector", "gatekeeper"):
        old = _local_governance_role_snippet(workdir, role=role, locale="en")
        if old:
            yaml_text = yaml_text.replace(old, _local_governance_role_snippet(workdir, role=role, locale="zh"))
    return yaml_text


def alignment_chinese_bundle_yaml_with_english_visible_names(workdir: str) -> str:
    yaml_text = alignment_chinese_bundle_yaml(workdir)
    replacements = {
        '  name: "对齐 Starter Bundle"': '  name: "Aligned Starter Bundle"',
        '  description: "由 Web alignment flow 生成的 bundle。"': ('  description: "Bundle generated by the Web alignment flow."'),
        '    name: "聚焦 Builder"': '    name: "Focused Builder"',
        '    name: "契约 Inspector"': '    name: "Contract Inspector"',
        '    name: "证据 Inspector"': '    name: "Evidence Inspector"',
        '    name: "审慎 GateKeeper"': '    name: "Conservative GateKeeper"',
    }
    for old, new in replacements.items():
        yaml_text = yaml_text.replace(old, new)
    return yaml_text


def alignment_improvement_bundle_yaml(workdir: str) -> str:
    yaml_text = alignment_bundle_yaml(workdir)
    return (
        yaml_text.replace(
            (
                "  Project the working agreement into a spec task contract for the focused starter slice, "
                "role handoffs from Builder / Inspectors / GateKeeper, and a workflow that routes evidence "
                "before final judgment. Future iterations stay anchored to this contract as new evidence, "
                "blockers, and handoffs appear, rather than treating one Agent pass or one review as enough. "
                "Prefer a smaller proven flow over polished but unproven breadth, "
                "and let GateKeeper reject speed or surface completeness when evidence is weak. "
                "Intermediate control points measure weak evidence and fake-done drift, trigger inspect / correct / halt "
                "decisions, and keep the required evidence target explicit. GateKeeper closes only when the spec, role "
                "evidence, and workflow handoffs prove the task is truly done. Evidence projection must "
                "distinguish Proven direct run proof, Weak indirect evidence, Unproven promised surfaces, Blocking "
                "fake-done findings, and visible Residual risk.\n"
            ),
            (
                "  Preserve the source Loop's stable task intent, workdir, and useful role posture while "
                "changing the feedback-driven governance delta across spec, roles, workflow, evidence "
                "expectations, and GateKeeper strictness. Future improvement iterations keep the source "
                "judgment anchored as new run evidence, coverage, evidence summary, and "
                "GateKeeper verdict should drive which claims become Proven, Weak, Unproven, Blocking, "
                "or visible Residual risk.\n"
            ),
        )
        .replace(
            "    - Prefer project-owned checks, direct run output, and concrete artifacts before screenshots or claims.\n",
            "    - Preserve source intent, but tighten evidence expectations from feedback, run evidence, coverage, and GateKeeper verdict before screenshots or claims.\n",
        )
        .replace(
            '  collaboration_intent: "Build one focused starter slice, then inspect the contract and evidence in sequence so weak evidence, drift, or fake done surface early, let those control points trigger repair or blocking, then let GateKeeper finish only when both inspection views support the task contract."',
            '  collaboration_intent: "Preserve the source Loop shape where it still fits, but route the feedback-driven evidence delta through contract and evidence review so weak evidence, evidence gaps, or fake done surface early before GateKeeper closes."',
        )
    )


def alignment_chinese_improvement_bundle_yaml(workdir: str) -> str:
    yaml_text = alignment_chinese_bundle_yaml(workdir)
    return (
        yaml_text.replace(
            (
                "  将工作协议投影到 spec 任务契约、Builder / Inspector / GateKeeper 角色交接，以及先汇集证据再裁决的 workflow。"
                "后续轮次会随着新证据、阻断项和 handoff 回到这份契约，而不是把一次 Agent 执行或一次 review 当成足够。"
                "优先选择小而已证明的主流程，而不是打磨充分但未证明的宽泛功能；证据薄弱时让 GateKeeper 拒绝速度或表面完整性。"
                "中间控制点要测量弱证据和假完成偏差，触发检查、纠正或暂停决策，并让所需证据目标保持明确。"
                "GateKeeper 只有在任务契约、角色证据和 workflow handoff 都证明真实完成时才收束。"
                "证据投影必须区分已证明的直接运行证据、弱证据、未证明的承诺面、阻断类假完成，以及可见残余风险。\n"
            ),
            (
                "  保留来源 Loop 的稳定任务意图、workdir 和有用角色姿态，同时把反馈驱动的治理变化投影到 spec、roles、workflow、证据期望和 GateKeeper 严格度。"
                "后续改进轮次会随着新的运行证据、coverage 和 GateKeeper verdict 回到来源判断。"
                "运行证据、coverage、evidence summary 和 GateKeeper verdict 应决定哪些 claim 进入已证明、弱证据、未证明、阻断或可见残余风险。\n"
            ),
        )
        .replace(
            "    - 优先使用项目内检查、直接运行输出和具体产物，而不是截图或口头声称。\n",
            "    - 保留来源意图，但根据反馈、运行证据、coverage 和 GateKeeper verdict 收紧证据期望，而不是依赖截图或口头声称。\n",
        )
        .replace(
            '  collaboration_intent: "先构建一个聚焦 starter slice，然后顺序检查契约和证据，让证据薄弱、偏差或假完成提前暴露，并由这些控制点触发修复或阻断；只有两个检查视角都支持任务契约时，GateKeeper 才能 finish。"',
            '  collaboration_intent: "保留来源 Loop 中仍然有效的形状，但把反馈驱动的证据变化通过契约和证据 review 暴露出来，让弱证据、证据缺口或假完成在 GateKeeper 收束前可见。"',
        )
    )


def alignment_bundle_yaml_with_unsupported_observed_workdir_claim(workdir: str) -> str:
    yaml_text = alignment_bundle_yaml(workdir)
    return yaml_text.replace(
        ("    Ship the focused starter experience in the target workdir with small, maintainable changes that preserve the primary user flow."),
        (
            "    Observed Workdir Snapshot shows a React frontend app with npm build scripts. "
            "Ship the focused starter experience with small, maintainable changes."
        ),
    )


def alignment_bundle_yaml_with_governance_markers_listed_as_facts(workdir: str) -> str:
    yaml_text = alignment_bundle_yaml(workdir).replace(_local_governance_bundle_sentence(workdir, locale="en"), "")
    yaml_text = yaml_text.replace(_local_governance_bundle_sentence(workdir, locale="zh"), "")
    for role in ("builder", "inspector", "gatekeeper"):
        yaml_text = yaml_text.replace(_local_governance_role_snippet(workdir, role=role, locale="en"), "")
        yaml_text = yaml_text.replace(_local_governance_role_snippet(workdir, role=role, locale="zh"), "")
    return yaml_text.replace(
        ("    Ship the focused starter experience in the target workdir with small, maintainable changes that preserve the primary user flow."),
        (
            "    Workdir Snapshot detected AGENTS.md, design/README.md, design/, and tests/. "
            "Ship the focused starter experience with small, maintainable changes."
        ),
    )


def alignment_bundle_yaml_with_lineage_metadata(workdir: str) -> str:
    return alignment_bundle_yaml(workdir).replace(
        '  description: "Bundle generated by the Web alignment flow."\n',
        '  description: "Bundle generated by the Web alignment flow."\n  source_bundle_id: "source_bundle_old"\n  revision: 2\n',
        1,
    )


def alignment_bundle_yaml_without_semantics(workdir: str) -> str:
    yaml_text = alignment_bundle_yaml(workdir)
    yaml_text = re.sub(
        r"\n    # Success Surface\n\n    - .+?\n(?=\n    # Fake Done)",
        "\n",
        yaml_text,
        flags=re.DOTALL,
    )
    return re.sub(
        r"\n    # Evidence Preferences\n\n    - .+?\n(?=\n    # Role Notes)",
        "\n",
        yaml_text,
        flags=re.DOTALL,
    )
