from __future__ import annotations

from loopora.executor_alignment_bundle_task_workflows_trust_governance_data_residency import (
    _replace_data_residency_task_workflow as _replace_data_residency_task_workflow,
)
from loopora.executor_alignment_bundle_task_workflows_trust_governance_kyc_aml import (
    _replace_kyc_aml_screening_task_workflow as _replace_kyc_aml_screening_task_workflow,
)
