from __future__ import annotations

from loopora.executor_alignment_agreement_task_responses_trust_access_authorization import (
    alignment_chinese_authorization_policy_agreement_response as alignment_chinese_authorization_policy_agreement_response,
    alignment_english_authorization_policy_agreement_response as alignment_english_authorization_policy_agreement_response,
    alignment_spanish_authorization_policy_agreement_response as alignment_spanish_authorization_policy_agreement_response,
)
from loopora.executor_alignment_agreement_task_responses_trust_access_breakglass import (
    alignment_chinese_support_impersonation_agreement_response as alignment_chinese_support_impersonation_agreement_response,
    alignment_english_support_impersonation_agreement_response as alignment_english_support_impersonation_agreement_response,
    alignment_spanish_support_impersonation_agreement_response as alignment_spanish_support_impersonation_agreement_response,
)
from loopora.executor_alignment_agreement_task_responses_trust_access_identity import (
    alignment_chinese_auth_session_token_lifecycle_agreement_response as alignment_chinese_auth_session_token_lifecycle_agreement_response,
    alignment_chinese_identity_sso_agreement_response as alignment_chinese_identity_sso_agreement_response,
    alignment_english_auth_session_token_lifecycle_agreement_response as alignment_english_auth_session_token_lifecycle_agreement_response,
    alignment_english_identity_sso_agreement_response as alignment_english_identity_sso_agreement_response,
    alignment_spanish_auth_session_token_lifecycle_agreement_response as alignment_spanish_auth_session_token_lifecycle_agreement_response,
    alignment_spanish_identity_sso_agreement_response as alignment_spanish_identity_sso_agreement_response,
)
