from __future__ import annotations

from loopora.executor_alignment_bundle_base_fixture import alignment_bundle_yaml as alignment_bundle_yaml
from loopora.executor_alignment_bundle_improvement_variants import (
    alignment_chinese_improvement_bundle_yaml as alignment_chinese_improvement_bundle_yaml,
    alignment_chinese_refactor_improvement_bundle_yaml as alignment_chinese_refactor_improvement_bundle_yaml,
    alignment_improvement_bundle_yaml as alignment_improvement_bundle_yaml,
)
from loopora.executor_alignment_bundle_invalid_variants import (
    alignment_bundle_yaml_with_governance_markers_listed_as_facts as alignment_bundle_yaml_with_governance_markers_listed_as_facts,
    alignment_bundle_yaml_with_lineage_metadata as alignment_bundle_yaml_with_lineage_metadata,
    alignment_bundle_yaml_with_unsupported_observed_workdir_claim as alignment_bundle_yaml_with_unsupported_observed_workdir_claim,
    alignment_bundle_yaml_without_semantics as alignment_bundle_yaml_without_semantics,
)
from loopora.executor_alignment_bundle_localized_variants import (
    alignment_chinese_bundle_yaml as alignment_chinese_bundle_yaml,
    alignment_chinese_bundle_yaml_with_english_visible_names as alignment_chinese_bundle_yaml_with_english_visible_names,
)
from loopora.executor_alignment_bundle_refund_variants import (
    alignment_chinese_refund_repair_bundle_yaml as alignment_chinese_refund_repair_bundle_yaml,
    alignment_refund_repair_bundle_yaml as alignment_refund_repair_bundle_yaml,
)
from loopora.executor_alignment_bundle_task_anchor import alignment_task_anchored_repair_bundle_yaml as alignment_task_anchored_repair_bundle_yaml
