from __future__ import annotations

from loopora.executor_alignment_bundle_task_spec_scaffolds_trust_access import (
    _append_authorization_policy_spec_notes as _append_authorization_policy_spec_notes,
    _append_support_impersonation_spec_notes as _append_support_impersonation_spec_notes,
    _append_identity_sso_spec_notes as _append_identity_sso_spec_notes,
    _append_auth_session_token_lifecycle_spec_notes as _append_auth_session_token_lifecycle_spec_notes,
)

from loopora.executor_alignment_bundle_task_spec_scaffolds_trust_governance import (
    _append_data_residency_spec_notes as _append_data_residency_spec_notes,
    _append_kyc_aml_screening_spec_notes as _append_kyc_aml_screening_spec_notes,
)

from loopora.executor_alignment_bundle_task_spec_scaffolds_trust_secrets import (
    _append_key_rotation_spec_notes as _append_key_rotation_spec_notes,
    _append_prompt_asset_ownership_spec_notes as _append_prompt_asset_ownership_spec_notes,
)
