from __future__ import annotations

import re

from loopora.executor_alignment_bundle_base_fixture import alignment_bundle_yaml
from loopora.executor_alignment_bundle_governance_fixture import (
    alignment_bundle_governance_role_snippet as _local_governance_role_snippet,
    alignment_bundle_governance_sentence as _local_governance_bundle_sentence,
)


def alignment_bundle_yaml_with_unsupported_observed_workdir_claim(workdir: str) -> str:
    yaml_text = alignment_bundle_yaml(workdir)
    return yaml_text.replace(
        (
            "    Ship the focused starter experience for the target user in the target workdir with small, maintainable changes that preserve the primary user-facing flow."
        ),
        (
            "    Observed Workdir Snapshot shows a React frontend app with npm build scripts. "
            "Ship the focused starter experience for the target user with small, maintainable changes."
        ),
    )


def alignment_bundle_yaml_with_governance_markers_listed_as_facts(workdir: str) -> str:
    yaml_text = alignment_bundle_yaml(workdir).replace(_local_governance_bundle_sentence(workdir, locale="en"), "")
    yaml_text = yaml_text.replace(_local_governance_bundle_sentence(workdir, locale="zh"), "")
    for role in ("builder", "inspector", "gatekeeper"):
        yaml_text = yaml_text.replace(_local_governance_role_snippet(workdir, role=role, locale="en"), "")
        yaml_text = yaml_text.replace(_local_governance_role_snippet(workdir, role=role, locale="zh"), "")
    return yaml_text.replace(
        (
            "    Ship the focused starter experience for the target user in the target workdir with small, maintainable changes that preserve the primary user-facing flow."
        ),
        (
            "    Workdir Snapshot detected AGENTS.md, design/README.md, design/, and tests/. "
            "Ship the focused starter experience for the target user with small, maintainable changes."
        ),
    )


def alignment_bundle_yaml_with_lineage_metadata(workdir: str) -> str:
    return alignment_bundle_yaml(workdir).replace(
        '  description: "Bundle generated by the Web alignment flow."\n',
        '  description: "Bundle generated by the Web alignment flow."\n  source_bundle_id: "source_bundle_old"\n  revision: 2\n',
        1,
    )


def alignment_bundle_yaml_without_semantics(workdir: str) -> str:
    yaml_text = alignment_bundle_yaml(workdir)
    yaml_text = re.sub(
        r"\n    # Success Surface\n\n    - .+?\n(?=\n    # Fake Done)",
        "\n",
        yaml_text,
        flags=re.DOTALL,
    )
    return re.sub(
        r"\n    # Evidence Preferences\n\n    - .+?\n(?=\n    # Role Notes)",
        "\n",
        yaml_text,
        flags=re.DOTALL,
    )
