from __future__ import annotations

from loopora.executor_alignment_bundle_governance_fixture import (
    alignment_bundle_governance_role_snippet,
    alignment_bundle_governance_sentence,
)


def alignment_bundle_yaml(workdir: str) -> str:
    local_governance_sentence = alignment_bundle_governance_sentence(workdir, locale="en")
    builder_governance = alignment_bundle_governance_role_snippet(workdir, role="builder", locale="en")
    inspector_governance = alignment_bundle_governance_role_snippet(workdir, role="inspector", locale="en")
    gatekeeper_governance = alignment_bundle_governance_role_snippet(workdir, role="gatekeeper", locale="en")
    return f"""version: 1
metadata:
  name: "Aligned Starter Bundle"
  description: "Bundle generated by the Web alignment flow."
collaboration_summary: |
  Project the working agreement into a spec task contract for the focused starter slice, role handoffs from Builder / Inspectors / GateKeeper, and a workflow that routes evidence before final judgment. Future iterations stay anchored to this contract as new evidence, blockers, and handoffs appear, rather than treating one Agent pass or one review as enough. Prefer a smaller proven flow over polished but unproven breadth, and let GateKeeper reject speed or surface completeness when evidence is weak. Intermediate control points measure weak evidence and fake-done drift, trigger inspect / correct / halt decisions, and keep the required evidence target explicit. GateKeeper closes only when the spec, role evidence, and workflow handoffs prove the task is truly done. Evidence projection must distinguish Proven direct run proof, Weak indirect evidence, Unproven promised surfaces, Blocking fake-done findings, and visible Residual risk.{local_governance_sentence}
loop:
  name: "Aligned Starter Bundle"
  workdir: "{workdir}"
  completion_mode: "gatekeeper"
  executor_kind: "codex"
  executor_mode: "preset"
  command_cli: ""
  command_args_text: ""
  model: ""
  reasoning_effort: ""
  iteration_interval_seconds: 0
  max_iters: 4
  max_role_retries: 1
  delta_threshold: 0.005
  trigger_window: 2
  regression_window: 2
spec:
  markdown: |
    # Task

    Ship the focused starter experience in the target workdir with small, maintainable changes that preserve the primary user flow.

    # Done When

    - The primary user flow works end to end.
    - The implementation is covered by project-owned evidence.

    # Guardrails

    - Keep changes scoped to the requested behavior.

    # Success Surface

    - The primary user flow is understandable, maintainable, and easy to extend after the first pass.

    # Fake Done

    - Do not pass with only a happy-path claim and no reproducible evidence.
    - Do not pass if the implementation lacks a handoff that explains what evidence was collected.

    # Evidence Preferences

    - Prefer project-owned checks, direct run output, and concrete artifacts before screenshots or claims.
    - Each role should leave a clear handoff note explaining what was changed, inspected, or blocked.
    - Intermediate control points should measure a key risk, trigger a continue / correct / halt decision, and keep the required evidence target explicit.
    - Final evidence should be bucketed as Proven, Weak, Unproven, Blocking, or Residual risk instead of flattened into one summary.

    # Residual Risk

    Accept minor polish gaps only when they are explicitly named and tracked as an owned follow-up; fail closed on unproven primary-flow behavior or weak verification evidence.

    # Role Notes

    ## Builder Notes

    Prefer a small maintainable patch over broad rewrites.

    ## Inspector Notes

    Collect reproducible evidence and call out missing proof plainly.

    ## GateKeeper Notes

    Fail closed when Done When, fake-done risks, and evidence preferences are not all satisfied.
role_definitions:
  - key: "builder"
    name: "Focused Builder"
    description: "Implements the smallest maintainable change."
    archetype: "builder"
    prompt_ref: "builder.md"
    prompt_markdown: |
      ---
      version: 1
      archetype: builder
      ---

      Build the focused starter slice carefully and keep the repo coherent. Leave a handoff that names the changed behavior, the verification evidence, and any blocker that should stop Inspector or GateKeeper.
{builder_governance}
    posture_notes: |
      Keep implementation narrow and leave the workspace easier to verify; prefer concrete evidence over broad feature spread.
    executor_kind: "codex"
    executor_mode: "preset"
    command_cli: ""
    command_args_text: ""
    model: ""
    reasoning_effort: ""
  - key: "contract-inspector"
    name: "Contract Inspector"
    description: "Checks the task contract, guardrails, fake-done risks, execution strategy, judgment tradeoffs, local governance, and residual-risk stance."
    archetype: "inspector"
    prompt_ref: "inspector.md"
    prompt_markdown: |
      ---
      version: 1
      archetype: inspector
      ---

      Inspect the Builder handoff against Done When, Guardrails, Fake Done, Evidence Preferences, Execution Strategy, Judgment Tradeoffs, Local Governance, and Residual Risk. Your handoff must identify contract mismatches, missing proof, sequencing drift, lowered tradeoffs, local-governance gaps, and any blocker that should prevent GateKeeper from finishing. When evidence is weak, name the decision it should trigger and how the next execution pass should change.
{inspector_governance}
    posture_notes: |
      Prefer contract-level proof over broad confidence; block when the delivered slice does not match the agreed scope or leaves fake-done risk unresolved.
    executor_kind: "codex"
    executor_mode: "preset"
    command_cli: ""
    command_args_text: ""
    model: ""
    reasoning_effort: ""
  - key: "evidence-inspector"
    name: "Evidence Inspector"
    description: "Collects reproducible evidence before sign-off."
    archetype: "inspector"
    prompt_ref: "inspector.md"
    prompt_markdown: |
      ---
      version: 1
      archetype: inspector
      ---

      Inspect from direct evidence, project-owned commands, and concrete artifacts. Your handoff must identify the strongest proof, missing proof, and any blocker that should prevent GateKeeper from finishing.
    posture_notes: |
      Prefer reproducible run output and concrete artifacts; block vague completion claims, screenshots without context, or unverified happy paths.
    executor_kind: "codex"
    executor_mode: "preset"
    command_cli: ""
    command_args_text: ""
    model: ""
    reasoning_effort: ""
  - key: "gatekeeper"
    name: "Conservative GateKeeper"
    description: "Fails closed when evidence is weak."
    archetype: "gatekeeper"
    prompt_ref: "gatekeeper.md"
    prompt_markdown: |
      ---
      version: 1
      archetype: gatekeeper
      ---

      Decide from direct evidence and do not accept vague completion claims. Finish only when the Builder and Inspector handoffs prove the task contract, execution strategy, judgment tradeoffs, local governance when present, and residual-risk stance; otherwise block with the smallest repair. Treat status-only checkpoints as insufficient; the control point must affect correction, closure, or residual-risk handoff.
{gatekeeper_governance}
    posture_notes: |
      Close only when the task and verification evidence agree; fail closed when handoff evidence is missing or weak.
    executor_kind: "codex"
    executor_mode: "preset"
    command_cli: ""
    command_args_text: ""
    model: ""
    reasoning_effort: ""
workflow:
  version: 1
  preset: "build_then_review"
  collaboration_intent: "Build one focused starter slice, then inspect the contract and evidence in sequence so weak evidence, drift, or fake done surface early, let those control points trigger repair or blocking, then let GateKeeper finish only when both inspection views support the task contract."
  roles:
    - id: "builder"
      role_definition_key: "builder"
    - id: "contract_inspector"
      role_definition_key: "contract-inspector"
    - id: "evidence_inspector"
      role_definition_key: "evidence-inspector"
    - id: "gatekeeper"
      role_definition_key: "gatekeeper"
  steps:
    - id: "builder_step"
      role_id: "builder"
    - id: "contract_inspection_step"
      role_id: "contract_inspector"
      inputs:
        handoffs_from: ["builder_step"]
        evidence_query:
          archetypes: ["builder"]
          limit: 12
        iteration_memory: "summary_only"
    - id: "evidence_inspection_step"
      role_id: "evidence_inspector"
      inputs:
        handoffs_from: ["builder_step"]
        evidence_query:
          archetypes: ["builder"]
          limit: 12
        iteration_memory: "summary_only"
    - id: "gatekeeper_step"
      role_id: "gatekeeper"
      on_pass: "finish_run"
      inputs:
        handoffs_from: ["contract_inspection_step", "evidence_inspection_step"]
        evidence_query:
          archetypes: ["inspector", "builder"]
          limit: 24
"""
