from __future__ import annotations

from loopora.executor_alignment_agreement_task_responses_product_search_ai import (
    alignment_english_search_index_consistency_agreement_response as alignment_english_search_index_consistency_agreement_response,
    alignment_chinese_search_index_consistency_agreement_response as alignment_chinese_search_index_consistency_agreement_response,
    alignment_spanish_search_index_consistency_agreement_response as alignment_spanish_search_index_consistency_agreement_response,
    alignment_english_search_quality_agreement_response as alignment_english_search_quality_agreement_response,
    alignment_chinese_search_quality_agreement_response as alignment_chinese_search_quality_agreement_response,
    alignment_spanish_search_quality_agreement_response as alignment_spanish_search_quality_agreement_response,
    alignment_english_rag_long_chain_agreement_response as alignment_english_rag_long_chain_agreement_response,
    alignment_chinese_rag_long_chain_agreement_response as alignment_chinese_rag_long_chain_agreement_response,
    alignment_spanish_rag_long_chain_agreement_response as alignment_spanish_rag_long_chain_agreement_response,
)
from loopora.executor_alignment_agreement_task_responses_product_operations import (
    alignment_english_inventory_reservation_consistency_agreement_response as alignment_english_inventory_reservation_consistency_agreement_response,
    alignment_chinese_inventory_reservation_consistency_agreement_response as alignment_chinese_inventory_reservation_consistency_agreement_response,
    alignment_spanish_inventory_reservation_consistency_agreement_response as alignment_spanish_inventory_reservation_consistency_agreement_response,
    alignment_english_analytics_experiment_instrumentation_agreement_response as alignment_english_analytics_experiment_instrumentation_agreement_response,
    alignment_chinese_analytics_experiment_instrumentation_agreement_response as alignment_chinese_analytics_experiment_instrumentation_agreement_response,
    alignment_spanish_analytics_experiment_instrumentation_agreement_response as alignment_spanish_analytics_experiment_instrumentation_agreement_response,
)
from loopora.executor_alignment_agreement_task_responses_product_engagement import (
    alignment_english_support_ticket_sla_agreement_response as alignment_english_support_ticket_sla_agreement_response,
    alignment_chinese_support_ticket_sla_agreement_response as alignment_chinese_support_ticket_sla_agreement_response,
    alignment_spanish_support_ticket_sla_agreement_response as alignment_spanish_support_ticket_sla_agreement_response,
    alignment_english_schedule_timezone_recurrence_agreement_response as alignment_english_schedule_timezone_recurrence_agreement_response,
    alignment_chinese_schedule_timezone_recurrence_agreement_response as alignment_chinese_schedule_timezone_recurrence_agreement_response,
    alignment_spanish_schedule_timezone_recurrence_agreement_response as alignment_spanish_schedule_timezone_recurrence_agreement_response,
    alignment_english_notification_subscription_deliverability_agreement_response as alignment_english_notification_subscription_deliverability_agreement_response,
    alignment_chinese_notification_subscription_deliverability_agreement_response as alignment_chinese_notification_subscription_deliverability_agreement_response,
    alignment_spanish_notification_subscription_deliverability_agreement_response as alignment_spanish_notification_subscription_deliverability_agreement_response,
)
