from __future__ import annotations

from collections.abc import Mapping

import loopora.first_use_web_recovery as _web_recovery
from loopora.app_state_readiness import app_state_report as app_state_report
from loopora.app_state_readiness import app_state_web_readiness_blockers as app_state_web_readiness_blockers
from loopora.first_use_action_readiness import first_use_action_by_kind as first_use_action_by_kind
from loopora.first_use_action_readiness import first_use_action_readiness_summary as first_use_action_readiness_summary
from loopora.first_use_action_readiness import first_use_actions as first_use_actions
from loopora.first_use_action_readiness import (
    project_first_use_action_readiness_summary as project_first_use_action_readiness_summary,
)
from loopora.first_use_route_projection import FIRST_USE_COMMAND_ACTION_KINDS as FIRST_USE_COMMAND_ACTION_KINDS
from loopora.first_use_route_projection import (
    FIRST_USE_FIT_REVIEW_INDEPENDENT_ACTIONS as FIRST_USE_FIT_REVIEW_INDEPENDENT_ACTIONS,
)
from loopora.first_use_route_projection import FIRST_USE_ROUTE_ACTION_KEYS as FIRST_USE_ROUTE_ACTION_KEYS
from loopora.first_use_route_projection import (
    FIRST_USE_SETUP_INDEPENDENT_ACTIONS as FIRST_USE_SETUP_INDEPENDENT_ACTIONS,
)
from loopora.first_use_route_projection import (
    FIRST_USE_SUPPORT_INHERITED_SETUP_BLOCKERS as FIRST_USE_SUPPORT_INHERITED_SETUP_BLOCKERS,
)
from loopora.first_use_route_projection import FirstUseRouteReadinessGate as FirstUseRouteReadinessGate
from loopora.first_use_route_projection import first_use_app_state_command_blockers as first_use_app_state_command_blockers
from loopora.first_use_route_projection import (
    first_use_app_state_readiness_blocker_kinds as first_use_app_state_readiness_blocker_kinds,
)
from loopora.first_use_route_projection import first_use_inherited_setup_blockers as first_use_inherited_setup_blockers
from loopora.first_use_route_projection import first_use_reviewed_setup_gate_blockers as first_use_reviewed_setup_gate_blockers
from loopora.first_use_route_projection import first_use_route_action_with_readiness as first_use_route_action_with_readiness
from loopora.first_use_route_projection import first_use_route_command_blockers as first_use_route_command_blockers
from loopora.first_use_route_projection import open_web_creation_choice_blockers as open_web_creation_choice_blockers
from loopora.first_use_route_projection import project_first_use_adapter_choices as project_first_use_adapter_choices
from loopora.first_use_route_projection import project_first_use_reviewed_setup_gate as project_first_use_reviewed_setup_gate
from loopora.first_use_route_projection import project_first_use_route_action_readiness as project_first_use_route_action_readiness
from loopora.first_use_route_projection import project_first_use_route_readiness_summary as project_first_use_route_readiness_summary
from loopora.first_use_web_recovery import WEB_ROUTE_BLOCKED_PREFLIGHT_STATUSES as WEB_ROUTE_BLOCKED_PREFLIGHT_STATUSES
from loopora.first_use_web_recovery import first_use_readiness_blocker_kinds as first_use_readiness_blocker_kinds
from loopora.first_use_web_recovery import first_use_web_creation_choice_blockers as first_use_web_creation_choice_blockers
from loopora.first_use_web_recovery import first_use_web_readiness_note as first_use_web_readiness_note
from loopora.first_use_web_recovery import first_use_web_recovery_actions as first_use_web_recovery_actions


def first_use_web_readiness_blockers(workdir_state: Mapping[str, object]) -> list[dict[str, str]]:
    return _web_recovery.first_use_web_readiness_blockers(
        workdir_state,
        app_state_report_fn=app_state_report,
        app_state_web_readiness_blockers_fn=app_state_web_readiness_blockers,
    )
