from __future__ import annotations

"""Residual-risk marker and regex assets."""

NO_RESIDUAL_RISK_MARKERS = {
    "none",
    "n/a",
    "na",
    "no residual risk",
    "no blocking residual risk",
    "no blocking residual risk was reported by gatekeeper",
    "no meaningful residual risk",
    "无",
    "无残余风险",
    "无明显残余风险",
    "无重大残余风险",
    "无有意义残余风险",
    "没有残余风险",
    "没有明显残余风险",
    "没有阻断残余风险",
    "没有重大残余风险",
    "没有有意义的残余风险",
}

VAGUE_RESIDUAL_RISK_MARKERS = {
    "some risk remains",
    "some residual risk remains",
    "residual risk remains",
    "risks remain",
    "there is residual risk",
    "remaining risk",
    "some risk is fine",
    "有残余风险",
    "仍有风险",
    "存在风险",
    "存在残余风险",
    "还有风险",
    "有些风险",
}

RESIDUAL_RISK_MANAGEMENT_MARKERS = {
    "accepted",
    "assigned",
    "assignee",
    "block closure",
    "blocks closure",
    "deferred",
    "documented",
    "explicitly name",
    "explicitly named",
    "fail closed",
    "follow-up",
    "followup",
    "handoff",
    "issue",
    "mitigation",
    "monitor",
    "must block",
    "next",
    "owned",
    "owner",
    "planned",
    "review",
    "revisit",
    "ticket",
    "tracked",
    "tracking",
    "人工",
    "具名",
    "后续",
    "复核",
    "审查",
    "工单",
    "已接受",
    "手动",
    "接管",
    "接受",
    "方案",
    "明确命名",
    "监控",
    "计划",
    "记录",
    "负责人",
    "负责",
    "处理",
    "失败关闭",
    "跟踪",
    "跟进",
    "追踪",
    "必须阻断",
    "显式声明",
}

RESIDUAL_RISK_EXCEPTION_MARKERS = {
    " except ",
    " but ",
    " however ",
    " other than ",
    " aside from ",
    " besides ",
    " though ",
    " unless ",
    "，但",
    "，但是",
    "，不过",
    "；但",
    "；但是",
    "；不过",
    " 但",
    " 但是",
    " 不过",
    "除了",
    "除 ",
    "之外",
    "仍有",
    "还有",
}

UNMANAGED_RESIDUAL_RISK_DETAIL_PATTERNS = (
    r"\bownerless\b",
    r"\bunowned\b",
    r"\b(?:no|without|missing)\s+(?:owner|assignee|follow[- ]?up|followup|ticket|tracking|mitigation|acceptance path)\b",
    r"\b(?:owner|assignee|follow[- ]?up|followup|ticket|tracking|mitigation|acceptance path)\s+(?:missing|absent|unknown)\b",
    r"无人(?:接管|负责|跟进)",
    r"没人(?:接管|负责|跟进)",
    r"没有(?:接管|负责人|负责|后续|跟进)",
    r"未(?:接管|分配|跟进)",
    r"无(?:负责人|后续|跟进)",
)

VAGUE_RESIDUAL_RISK_ACCEPTANCE_PATTERNS = (
    r"\b(?:some|any|residual|remaining)\s+(?:residual\s+)?risks?\b.{0,40}\b(?:accepted|acceptable|allowed|fine|ok|okay)\b",
    r"\b(?:accepted|acceptable|allowed|fine|ok|okay)\b.{0,40}\b(?:some|any|residual|remaining)\s+(?:residual\s+)?risks?\b",
    r"(?:有些|一些|部分)?(?:残余|剩余)?风险.{0,16}(?:可以)?(?:接受|可接受|允许)",
    r"(?:接受|可接受|允许).{0,16}(?:有些|一些|部分)?(?:残余|剩余)?风险",
)

RESIDUAL_RISK_HANDOFF_MARKERS = {
    "assigned",
    "assignee",
    "follow-up",
    "followup",
    "handoff",
    "issue",
    "mitigation",
    "monitor",
    "next",
    "owned",
    "owner",
    "planned",
    "revisit",
    "ticket",
    "tracked",
    "tracking",
    "具名",
    "后续",
    "复核",
    "工单",
    "接管",
    "方案",
    "明确命名",
    "监控",
    "计划",
    "记录",
    "负责人",
    "负责",
    "处理",
    "跟踪",
    "跟进",
    "追踪",
    "显式声明",
}
