from __future__ import annotations

# Compound no-change markers must stay before their shorter base phrases; otherwise
# removing only the base phrase leaves contrastive words such as "但是" or "but".
AGREEMENT_NO_CHANGE_MARKERS: tuple[str, ...] = (
    "但是不需要修改",
    "但不需要修改",
    "不过不需要修改",
    "不需要修改",
    "但是不用修改",
    "但不用修改",
    "不过不用修改",
    "不用修改",
    "但是无需修改",
    "但无需修改",
    "不过无需修改",
    "无需修改",
    "但是不需要调整",
    "但不需要调整",
    "不过不需要调整",
    "不需要调整",
    "但是不用调整",
    "但不用调整",
    "不过不用调整",
    "不用调整",
    "但是无需调整",
    "但无需调整",
    "不过无需调整",
    "无需调整",
    "但是不需要改",
    "但不需要改",
    "不过不需要改",
    "不需要改",
    "但是不用改",
    "但不用改",
    "不过不用改",
    "不用改",
    "但是无需改",
    "但无需改",
    "不过无需改",
    "无需改",
    "调整后的工作协议",
    "调整后的协议",
    "调整后的方案",
    "调整后的方向",
    "but no changes",
    "but no change",
    "but without changes",
    "no changes",
    "no change",
    "without changes",
)

AGREEMENT_ADJUSTMENT_TOKENS: tuple[str, ...] = (
    "不确认",
    "不同意",
    "不要",
    "先别",
    "不是",
    "不对",
    "但是",
    "不过",
    "但",
    "改成",
    "改为",
    "改一下",
    "增加",
    "补充",
    "添加",
    "删除",
    "去掉",
    "修改",
    "调整",
    "换成",
    "再改",
    " no",
    "not",
    " but",
    "add",
    "change",
    "delete",
    "remove",
    "revise",
    "adjust",
    "instead",
)

AGREEMENT_CONFIRMATION_TOKENS: tuple[str, ...] = (
    "确认",
    "同意",
    "可以",
    "就这样",
    "按这个",
    "没问题",
    "继续",
    "ok",
    "yes",
    "confirm",
    "approved",
    "go ahead",
    "proceed",
)
