from __future__ import annotations

"""Strategy Source definitions and legacy workflow-format compatibility rules."""

from loopora.strategy_source_constants import (
    ARCHETYPES,
    LEGACY_ROLE_BY_ARCHETYPE,
    PROMPT_FILES,
    ROLE_EXECUTION_FIELDS,
    ROLE_POSTURE_FIELDS,
    STRATEGY_SOURCE_VERSION,
)
from loopora.strategy_source_controls import (
    STRATEGY_SOURCE_CONTROL_AFTER_RE as STRATEGY_SOURCE_CONTROL_AFTER_RE,
    STRATEGY_SOURCE_CONTROL_ARCHETYPES as STRATEGY_SOURCE_CONTROL_ARCHETYPES,
    STRATEGY_SOURCE_CONTROL_CALL_KEYS as STRATEGY_SOURCE_CONTROL_CALL_KEYS,
    STRATEGY_SOURCE_CONTROL_KEYS as STRATEGY_SOURCE_CONTROL_KEYS,
    STRATEGY_SOURCE_CONTROL_MODES as STRATEGY_SOURCE_CONTROL_MODES,
    STRATEGY_SOURCE_CONTROL_SIGNALS as STRATEGY_SOURCE_CONTROL_SIGNALS,
    STRATEGY_SOURCE_CONTROL_WHEN_KEYS as STRATEGY_SOURCE_CONTROL_WHEN_KEYS,
    WORKFLOW_CONTROL_AFTER_RE as WORKFLOW_CONTROL_AFTER_RE,
    WORKFLOW_CONTROL_ARCHETYPES as WORKFLOW_CONTROL_ARCHETYPES,
    WORKFLOW_CONTROL_CALL_KEYS as WORKFLOW_CONTROL_CALL_KEYS,
    WORKFLOW_CONTROL_KEYS as WORKFLOW_CONTROL_KEYS,
    WORKFLOW_CONTROL_MODES as WORKFLOW_CONTROL_MODES,
    WORKFLOW_CONTROL_SIGNALS as WORKFLOW_CONTROL_SIGNALS,
    WORKFLOW_CONTROL_WHEN_KEYS as WORKFLOW_CONTROL_WHEN_KEYS,
    normalize_strategy_source_control as normalize_strategy_source_control,
    normalize_strategy_source_control_call as normalize_strategy_source_control_call,
    normalize_strategy_source_control_id as normalize_strategy_source_control_id,
    normalize_strategy_source_control_max_fires as normalize_strategy_source_control_max_fires,
    normalize_strategy_source_control_mode as normalize_strategy_source_control_mode,
    normalize_strategy_source_control_when as normalize_strategy_source_control_when,
    normalize_strategy_source_controls as normalize_strategy_source_controls,
    normalize_workflow_control as normalize_workflow_control,
    normalize_workflow_control_call as normalize_workflow_control_call,
    normalize_workflow_control_id as normalize_workflow_control_id,
    normalize_workflow_control_max_fires as normalize_workflow_control_max_fires,
    normalize_workflow_control_mode as normalize_workflow_control_mode,
    normalize_workflow_control_when as normalize_workflow_control_when,
    normalize_workflow_controls as normalize_workflow_controls,
)
from loopora.strategy_source_execution_settings import (
    default_role_execution_settings as default_role_execution_settings,
    default_strategy_role_execution_settings as default_strategy_role_execution_settings,
    normalize_role_execution_settings as normalize_role_execution_settings,
    normalize_strategy_role_execution_settings as normalize_strategy_role_execution_settings,
    role_uses_execution_snapshot as role_uses_execution_snapshot,
    strategy_role_uses_execution_snapshot as strategy_role_uses_execution_snapshot,
)
from loopora.strategy_source_errors import StrategySourceError as StrategySourceError
from loopora.strategy_source_errors import WorkflowError as WorkflowError
from loopora.strategy_source_files import (
    load_strategy_source_file as load_strategy_source_file,
    load_workflow_file as load_workflow_file,
    resolve_prompt_files as resolve_prompt_files,
    resolve_strategy_prompt_files as resolve_strategy_prompt_files,
)
from loopora.strategy_source_prompt_assets import (
    PROMPT_ASSET_DIR as PROMPT_ASSET_DIR,
    PROMPT_FRONT_MATTER_RE as PROMPT_FRONT_MATTER_RE,
    SPEC_PRACTICE_ASSET_DIR as SPEC_PRACTICE_ASSET_DIR,
    available_prompt_templates as available_prompt_templates,
    available_strategy_prompt_templates as available_strategy_prompt_templates,
    builtin_prompt_files_for_strategy_source as builtin_prompt_files_for_strategy_source,
    builtin_prompt_files_for_workflow as builtin_prompt_files_for_workflow,
    builtin_prompt_markdown as builtin_prompt_markdown,
    builtin_prompt_markdown_by_locale as builtin_prompt_markdown_by_locale,
    builtin_strategy_prompt_markdown as builtin_strategy_prompt_markdown,
    builtin_strategy_prompt_markdown_by_locale as builtin_strategy_prompt_markdown_by_locale,
    load_prompt_file as load_prompt_file,
    load_strategy_prompt_file as load_strategy_prompt_file,
    localized_prompt_ref as localized_prompt_ref,
    normalize_prompt_locale as normalize_prompt_locale,
    normalize_prompt_ref as normalize_prompt_ref,
    parse_prompt_markdown as parse_prompt_markdown,
    prompt_asset_path as prompt_asset_path,
    validate_prompt_markdown as validate_prompt_markdown,
)
from loopora.strategy_source_presets import (
    DEFAULT_STRATEGY_SOURCE_PRESET as DEFAULT_STRATEGY_SOURCE_PRESET,
    DEFAULT_WORKFLOW_PRESET as DEFAULT_WORKFLOW_PRESET,
    STRATEGY_SOURCE_PRESETS as STRATEGY_SOURCE_PRESETS,
    WORKFLOW_PRESETS as WORKFLOW_PRESETS,
    PresetRoleSpec as PresetRoleSpec,
    PresetStepSpec as PresetStepSpec,
    StrategySourcePresetDefinitionSpec as StrategySourcePresetDefinitionSpec,
    WorkflowPresetDefinitionSpec as WorkflowPresetDefinitionSpec,
    build_preset_strategy_source as build_preset_strategy_source,
    build_preset_workflow as build_preset_workflow,
    builtin_spec_practice as builtin_spec_practice,
    preset_names as preset_names,
    strategy_source_preset_copy as strategy_source_preset_copy,
    strategy_source_preset_names as strategy_source_preset_names,
    strategy_source_preset_options as strategy_source_preset_options,
    workflow_preset_copy as workflow_preset_copy,
    workflow_preset_options as workflow_preset_options,
)
from loopora.strategy_source_normalization import (
    normalize_preset_strategy_source as normalize_preset_strategy_source,
    normalize_preset_workflow as normalize_preset_workflow,
    normalize_strategy_source as normalize_strategy_source,
    normalize_workflow as normalize_workflow,
    require_strategy_source_entries as require_strategy_source_entries,
    require_workflow_entries as require_workflow_entries,
    strategy_source_requests_preset as strategy_source_requests_preset,
    workflow_requests_preset as workflow_requests_preset,
)
from loopora.strategy_source_roles import (
    display_name_for_archetype as display_name_for_archetype,
    normalize_archetype as normalize_archetype,
    normalize_role_display_name as normalize_role_display_name,
    normalize_role_models as normalize_role_models,
    normalize_strategy_archetype as normalize_strategy_archetype,
    normalize_strategy_role_display_name as normalize_strategy_role_display_name,
    normalize_strategy_role_models as normalize_strategy_role_models,
    normalize_strategy_source_role as normalize_strategy_source_role,
    normalize_strategy_source_roles as normalize_strategy_source_roles,
    normalize_workflow_role as normalize_workflow_role,
    normalize_workflow_roles as normalize_workflow_roles,
    strategy_archetype_display_name as strategy_archetype_display_name,
)
from loopora.strategy_source_steps import (
    PARALLEL_GROUP_ARCHETYPES as PARALLEL_GROUP_ARCHETYPES,
    STEP_ACTION_POLICY_KEYS as STEP_ACTION_POLICY_KEYS,
    STEP_ACTION_POLICY_WORKSPACES as STEP_ACTION_POLICY_WORKSPACES,
    STEP_EVIDENCE_QUERY_KEYS as STEP_EVIDENCE_QUERY_KEYS,
    STEP_EXECUTION_FIELDS as STEP_EXECUTION_FIELDS,
    STEP_INPUT_KEYS as STEP_INPUT_KEYS,
    STEP_ITERATION_MEMORY_POLICIES as STEP_ITERATION_MEMORY_POLICIES,
    default_step_action_policy as default_step_action_policy,
    default_step_execution_settings as default_step_execution_settings,
    default_step_inherit_session as default_step_inherit_session,
    default_strategy_step_action_policy as default_strategy_step_action_policy,
    default_strategy_step_execution_settings as default_strategy_step_execution_settings,
    default_strategy_step_inherit_session as default_strategy_step_inherit_session,
    normalize_step_action_policy as normalize_step_action_policy,
    normalize_step_action_policy_workspace as normalize_step_action_policy_workspace,
    normalize_step_evidence_archetypes as normalize_step_evidence_archetypes,
    normalize_step_evidence_limit as normalize_step_evidence_limit,
    normalize_step_evidence_query as normalize_step_evidence_query,
    normalize_step_handoffs_from as normalize_step_handoffs_from,
    normalize_step_inherit_session as normalize_step_inherit_session,
    normalize_step_inputs as normalize_step_inputs,
    normalize_step_iteration_memory as normalize_step_iteration_memory,
    normalize_step_on_pass as normalize_step_on_pass,
    normalize_step_parallel_group as normalize_step_parallel_group,
    normalize_step_policy_boolean as normalize_step_policy_boolean,
    normalize_strategy_source_step as normalize_strategy_source_step,
    normalize_strategy_source_steps as normalize_strategy_source_steps,
    normalize_strategy_step_action_policy as normalize_strategy_step_action_policy,
    normalize_strategy_step_action_policy_workspace as normalize_strategy_step_action_policy_workspace,
    normalize_strategy_step_evidence_archetypes as normalize_strategy_step_evidence_archetypes,
    normalize_strategy_step_evidence_limit as normalize_strategy_step_evidence_limit,
    normalize_strategy_step_evidence_query as normalize_strategy_step_evidence_query,
    normalize_strategy_step_handoffs_from as normalize_strategy_step_handoffs_from,
    normalize_strategy_step_inherit_session as normalize_strategy_step_inherit_session,
    normalize_strategy_step_inputs as normalize_strategy_step_inputs,
    normalize_strategy_step_iteration_memory as normalize_strategy_step_iteration_memory,
    normalize_strategy_step_on_pass as normalize_strategy_step_on_pass,
    normalize_strategy_step_parallel_group as normalize_strategy_step_parallel_group,
    normalize_workflow_step as normalize_workflow_step,
    normalize_workflow_steps as normalize_workflow_steps,
    strategy_source_step_parallel_group as strategy_source_step_parallel_group,
    validate_parallel_group_contiguity as validate_parallel_group_contiguity,
    validate_parallel_group_size as validate_parallel_group_size,
    validate_parallel_group_step as validate_parallel_group_step,
    validate_strategy_source_parallel_groups as validate_strategy_source_parallel_groups,
    validate_workflow_parallel_groups as validate_workflow_parallel_groups,
    workflow_step_parallel_group as workflow_step_parallel_group,
)
from loopora.strategy_source_validation import (
    STRATEGY_SOURCE_SAFE_IDENTIFIER_RE as STRATEGY_SOURCE_SAFE_IDENTIFIER_RE,
    WORKFLOW_SAFE_IDENTIFIER_RE as WORKFLOW_SAFE_IDENTIFIER_RE,
    normalize_strategy_source_identifier as normalize_strategy_source_identifier,
    normalize_strategy_source_version as normalize_strategy_source_version,
    normalize_workflow_identifier as normalize_workflow_identifier,
    normalize_workflow_version as normalize_workflow_version,
)
from loopora.strategy_source_warnings import (
    has_finish_gatekeeper_step as has_finish_gatekeeper_step,
    strategy_source_guide_input_warnings as strategy_source_guide_input_warnings,
    strategy_source_has_finish_gatekeeper_step as strategy_source_has_finish_gatekeeper_step,
    strategy_source_warnings as strategy_source_warnings,
    workflow_guide_input_warnings as workflow_guide_input_warnings,
    workflow_warnings as workflow_warnings,
)

STRATEGY_SOURCE_ARCHETYPES = ARCHETYPES
WORKFLOW_VERSION = STRATEGY_SOURCE_VERSION
LEGACY_STRATEGY_ROLE_BY_ARCHETYPE = LEGACY_ROLE_BY_ARCHETYPE
STRATEGY_PROMPT_FILES = PROMPT_FILES
STRATEGY_ROLE_EXECUTION_FIELDS = ROLE_EXECUTION_FIELDS
STRATEGY_ROLE_POSTURE_FIELDS = ROLE_POSTURE_FIELDS
