from __future__ import annotations

AGENT_ENTRY_GEN_CONTRACT_SNIPPETS = (
    "## Purpose",
    "## Run Command",
    "## Recovery",
    "## Work Panel Use",
    "## Role Dispatch",
    "## Result Template",
    "## Proof Boundary",
    "## Failure Modes",
    "Enter Loopora's planning stage",
    "agent_v3_envelope",
    "Compile, revise, repair, or tighten",
    "change the judgment structure",
    "tell them to use `/loopora-run`",
    "start fresh, recreate the bundle, or not reuse the old Loop",
    '--message "<non-empty short task summary>"',
    'with `--message "<non-empty short task summary>"` but without `--bundle-file`',
    "Loopora fit must say why one Agent pass, one review, direct chat / direct answer, one-off task handling, or benchmark/test-harness-only validation is not enough",
    "new evidence, handoffs, or a GateKeeper verdict",
    "compile them into Builder reading, Inspector / Custom verification, and GateKeeper Weak / Unproven / Blocking responsibility rather than a marker list",
    "Loopora fit reason, high-signal objects, success outcome categories, fake-done risk categories, concrete evidence modes, execution priorities, judgment tradeoffs, local governance responsibilities, and risk terms",
    "Check Loopora fit and judgment sufficiency before authoring a Loop plan file",
    "If Loopora fit is false",
    "ask one focused question",
    "return a Web review prefill",
    "put that answer into `--message`",
    "only a rough goal without fake-done risk, evidence, or judgment tradeoff signal",
    "instead of synthesizing a complete READY candidate",
    "execution strategy",
    "what to build, prove, repair, narrow, expand, or defer first",
    "judgment tradeoffs",
    "local governance responsibilities",
    "owner, follow-up, or acceptance path",
    "do not let a bundle pass merely because it repeats one or two object words from the task",
    "Do not invent human judgment just to pass validation",
    "raw.legacy",
    "native_surface",
    "ready_review_projection",
    "same-session run command",
    "`loop_recovery=plan_message_required`",
    "question_action",
    "recommended_reply_shape",
    "decision_impact",
    "task_message_template",
    "first_task_message_example",
    "debug_cli_example_command",
    "review_status",
    "after_review_slash_command",
    "after_review_cli_command",
    "after_review_command",
    "ready_slash_command",
    "ready_cli_command",
    "ready_next_step",
    "repair_slash_command",
    "repair_cli_command",
    "repair_task_message",
    "preserves `repair_task_message` and `repair_focus`",
    "review_before_loop",
    "confirm that review summary and preview URL",
    "do not start the run from Web",
    "repair the plan file",
    "Loop preview",
    "Web review",
)

AGENT_ENTRY_LOOP_CONTRACT_SNIPPETS = (
    "## Purpose",
    "## Run Command",
    "## Recovery",
    "## Work Panel Use",
    "## Role Dispatch",
    "## Result Template",
    "## Proof Boundary",
    "## Failure Modes",
    "Enter Loopora's run stage",
    "agent_v3_envelope",
    "run, resume, continue, keep going, close evidence gaps",
    "tell them to use `/loopora-plan` or Web review first",
    "Do not silently rewrite the Loop from `/loopora-run`",
    "agent_v3_envelope.summary",
    "agent_work_panel:",
    "`state`, `next_action`, `evidence_focus`, and `todo_items`",
    "main Agent session",
    "loopora_host_dispatch",
    "role_dispatch.target_agent",
    "role_dispatch.target_agent_config_exists",
    "judgment_contract",
    "next_step.judgment_contract",
    "next_step.required_coverage",
    "next_step.output_schema",
    "next_step.action_policy",
    "next_step.known_evidence_ids",
    "next_step.known_evidence_refs",
    "next_step.native_todo",
    "next_step.submit_hint.result_template_absolute_path",
    "Read the returned JSON, even if the command exits nonzero",
    "`loop_recovery=choose_recoverable_context`",
    "selection_hint",
    "runnable/non-runnable counts",
    "non-runnable choices' `preview_path`, `validation_error`, `repair_focus`",
    "`loop_recovery=plan_first`",
    "Report `required_inputs`, `ask_user`, one main-session `question_action`, `recommended_reply_shape`, `decision_impact`, `example_user_reply`, and `next_plan_command`",
    "if the answer is only a rough goal",
    "rather than synthesizing a READY candidate",
    "`loop_recovery=active_run_conflict`",
    "`loop_recovery=finish_web_review`",
    "review_status",
    "after_review_command",
    "`loop_recovery=repair_candidate_plan_file`",
    "repair_task_message",
    "preserves `repair_task_message` and `repair_focus`",
    "Do not collapse these recovery states into a generic",
    "terminal `task_verdict_status` / `task_verdict_summary`",
    "If the command returns `loop_recovery`, report that recovery path and stop",
    "loopora_result_contract",
    "native_trace_contract",
    "Do not hand-write the wrapper from memory",
    "Fill only the `result` object",
    "submit_repair=repair_result_json",
    "summary.task_proven",
    "summary.next_step.iteration_repair",
    "next_agent_command",
    "task_proven",
    "task_outcome",
    "lifecycle_vs_task",
    "summary.continuation",
    "next_step.iteration_repair",
    "next_step.submit_hint.command",
    "run.task_verdict",
    "task_next_action",
    "task_next_action.kind",
    "task_next_action.next_loop_command",
    "continue_evidence",
    "already_passed",
    "submitted_step.evidence_refs",
    "submitted_step.handoff_absolute_path",
    "submitted_step.blocking_items",
    "submitted_step.recommended_next_action",
    "next_step.prompt",
    "next_step.context_absolute_path",
)

AGENT_ORCHESTRATOR_CONTRACT_SNIPPETS = (
    "next_step.judgment_contract",
    "next_step.prompt",
    "next_step.output_schema",
    "next_step.action_policy",
    "next_step.known_evidence_ids",
    "next_step.known_evidence_refs",
    "next_step.native_todo",
    "next_step.submit_hint.result_template_absolute_path",
    "native_trace_ref",
    "loopora_result_contract",
    "schema-shaped `result` scaffold",
    "replace every `null` placeholder",
    "submit_repair=repair_result_json",
    "task_next_action.kind=continue_evidence",
    "task_next_action.kind=already_passed",
    "context_absolute_path",
)

EXPECTED_NATIVE_PACKAGING = {
    "behavior_source": "loopora_core_and_managed_references",
    "host_entries": "generated_thin_project_local_packaging",
    "projection_policy": "generated_projections_caches_and_marketplace_metadata_are_not_canonical_behavior",
    "component_export": "prompt_wrappers_cross_host_skill_exports_and_external_skill_installers_are_guidance_not_adapter_parity_or_install_proof",
    "install_scope": "project_local_no_global_marketplace_or_skill_cache",
    "entry_visibility": "adapter_project_entries_checked_not_global_skill_sync_assumed",
    "shadow_policy": "stale_duplicate_or_shadow_entries_are_visibility_risks_not_loopora_proof",
    "registry_policy": "remote_marketplaces_are_discovery_not_runtime_dependency_or_proof",
    "link_policy": "global_or_external_symlinks_are_hints_not_loopora_entry_proof",
    "runtime_bundle": "entries_roles_references_and_state_checked_together",
    "manifest": "managed_files_sha256_manifest",
    "drift_check": "loopora_check_reports_missing_stale_or_unowned_files",
    "update_policy": "explicit_check_or_init_only_no_background_auto_update",
    "repair": "regenerate_loopora_managed_packaging_only",
}

EXPECTED_NATIVE_CONTEXT_LOADING = {
    "entry_prompt": "thin_dispatcher",
    "summary_first": [
        "agent_v3_envelope.summary",
    ],
    "reference_loading": "on_demand_from_reference_paths",
    "full_payload": "open_after_compact_summary",
    "host_memory": "host_owned_hint_not_binding_or_evidence",
    "memory_store": "external_memory_stores_indexes_and_memory_mcp_are_hints_not_loopora_context_or_proof",
    "template_context": "host_command_templates_playbooks_and_dynamic_prompts_are_hints_not_loopora_reviewed_workflow",
    "workflow_kits": "external_spec_workflows_prd_packs_quality_gate_recipes_and_workflow_kits_are_guidance_not_loopora_reviewed_workflow_install_proof_or_evidence",
    "role_catalogs": "external_agent_catalogs_subagent_libraries_and_role_marketplaces_are_selection_hints_not_loopora_role_contract_or_policy",
    "compaction_context": "host_compaction_summaries_are_hints_not_loopora_binding_or_proof",
    "host_context": "host_loaded_skills_commands_agents_editor_context_and_ide_bridges_are_hints_not_loopora_binding_contract_or_evidence",
    "catalog_context": "marketplace_catalogs_and_uninstalled_components_are_not_loopora_context_or_proof",
}

EXPECTED_NATIVE_PERMISSION_BOUNDARY = {
    "policy_owner": "host_agent_and_user",
    "loopora_policy": "do_not_bypass_or_downgrade_host_permissions",
    "role_scope": "use_host_native_role_tool_allowlists",
    "approval_prompts": "pause_for_host_approval_or_report_blocked",
    "mode_switching": "host_agent_user_owned_not_changed_by_loopora",
    "automation": "auto_approvers_full_access_and_no_sandbox_are_host_opt_in_not_loopora_policy",
    "sandbox_runners": "external_containers_devcontainers_microvms_and_remote_runners_are_host_isolation_not_loopora_workspace_permission_or_proof",
    "security_guardrails": "external_security_scanners_guardrails_and_agent_firewalls_are_host_controls_not_loopora_permission_policy_or_evidence",
    "deny_rules": "respect_host_deny_rules_before_loopora_submit",
    "proof_boundary": "approval_is_not_task_evidence",
}

EXPECTED_NATIVE_TOOLING_BOUNDARY = {
    "mcp_servers": "host_owned_not_installed_or_enabled_by_loopora",
    "external_tools": "use_host_available_tools_without_relaxing_permissions",
    "tool_outputs": "proof_only_when_submitted_as_loopora_evidence",
}

EXPECTED_NATIVE_OBSERVABILITY = {
    "agent_activity": "host_status_or_compact_summary_only",
    "web_view": "observe_evidence_gaps_and_verdicts",
    "permission_prompts": "host_agent_owns_approval_flow",
    "hook_events": "observation_only_until_submitted_as_loopora_evidence",
    "hook_protocol": "adapter_specific_no_cross_host_parity_assumption",
    "hook_runners": "external_hook_runners_are_opt_in_host_automation_not_loopora_dispatch",
    "statusline_metrics": "host_statusline_usage_cost_context_and_git_metrics_are_observation_not_loopora_proof",
    "task_trackers": "external_task_managers_todos_backlogs_and_subagent_statuses_are_coordination_not_loopora_lifecycle_or_proof",
    "remote_controls": "ci_actions_pr_bots_comment_triggers_dashboards_webhooks_and_background_consoles_are_host_control_not_loopora_activation_dispatch_or_proof",
    "diagnostic_traces": "external_trace_viewers_api_proxies_session_recorders_and_usage_analyzers_are_diagnostics_not_loopora_evidence_or_verdict",
    "progress_signal": "activity_status_is_not_task_proof",
    "proof_signal": "loopora_evidence_refs_and_task_verdict",
}

EXPECTED_NATIVE_EXPERIENCE_CAPABILITIES = {
    "role_dispatch_guidance": "managed_entries_name_the_host_native_role_agent_and_stop_before_inline_submit",
    "todo_guidance": "native_todo_should_create_or_update_host_todo_when_available_not_evidence",
    "user_question_guidance": "ask_user_routes_missing_loop_judgment_to_main_agent_session",
    "native_trace_optional": "preserve_official_subagent_or_task_trace_when_available_do_not_invent",
    "technical_handoff_paths": "context_capsule_result_template_and_submit_command_remain_available_below_work_panel",
}
