from __future__ import annotations

AGENT_ENTRY_GEN_CONTRACT_SNIPPETS = (
    "## Purpose",
    "## Run Command",
    "## Recovery",
    "## Work Panel Use",
    "## Role Dispatch",
    "## Result Template",
    "## Proof Boundary",
    "Do not run project proof commands before planning",
    "## Failure Modes",
    "Enter Loopora's planning stage",
    "`/loopora-plan` is an interactive alignment conversation, not a one-prompt compiler",
    "form a working agreement, wait for explicit confirmation",
    "top-level JSON `summary`",
    "Do not run project tests, proof commands, smoke checks, or baseline checks before planning",
    "planning should conduct interactive alignment from current task context and managed references",
    "never pipe it through `head`, `tail`, `sed`, `python -c`, `jq`, `grep`, `wc`, `tee`, or `2>&1 | ...`",
    "Read managed references from exact known project paths with host file-read capability when available",
    "Partial or filtered reference output is not stable entry validation",
    "After writing a candidate plan file, verify only existence/readability",
    "do not inspect candidate snippets with `head`, `head -1`, `cat`, `sed`, `grep`, `jq`, `wc`",
    "Do not wrap either command in `tee`, `wc`, `head`, `tail`, `sed`, `jq`, `grep`, `python -c`, line/byte-count commands, or shell pipelines",
    "do not redirect managed JSON to `/tmp`",
    "compile, revise, repair, or tighten",
    "change the judgment structure",
    "tell them to use `/loopora-run`",
    "start fresh, recreate the bundle, or not reuse the old Loop",
    "failed `Skill` tool invocation with `disable-model-invocation` is an entry-visibility signal",
    "not permission to simulate `/loopora-plan` through a generic `Agent` or `Task` call",
    "Do not invoke adjacent Loopora, alignment, bundle-generation, or marketplace skills such as `loopora-task-alignment`",
    "Do not inspect `$HOME/.claude`, global skill directories, Loopora manifests, binary/PATH probes",
    "`which loopora`, `command -v loopora`, `type loopora`, `echo $PATH`",
    "`loopora --version`, `loopora --help`, `loopora init claude`, `loopora agent claude check`",
    "Do not run the combined preflight `which loopora && loopora --version`",
    "directory-listing preflights such as `ls`",
    "After host-native confirmation and candidate authoring, the next Bash action should run candidate validation",
    "Create/check a candidate file only after explicit confirmation",
    "parent directories, or broad project/file discovery to verify the entry",
    "the next Bash action should run candidate validation",
    '--message "<non-empty task context>"',
    'with `--message "<non-empty task context>"` but without `--bundle-file`',
    "## Message Preservation",
    "Use `--message` for the current task context, not a lossy title",
    "do not compress away the fit rationale, evidence modes, blockers, exception categories",
    "Loopora fit must say why one Agent pass, one review, direct chat / direct answer, one-off task handling, or benchmark/test-harness-only validation is not enough",
    "new evidence, handoffs, or a GateKeeper verdict",
    "compile them into Builder reading, Inspector / Custom verification, and GateKeeper Weak / Unproven / Blocking responsibility rather than a marker list",
    "For governance-marker repair, keep explicit responsibility sentences close to the marker text",
    "Builder reads and follows applicable project-local governance before edits",
    "Inspector verifies related design/tests/governance evidence",
    "GateKeeper treats skipped governance or missing expected validation as Weak, Unproven, or Blocking",
    "Loopora fit reason, high-signal objects, success outcome categories, fake-done risk categories, concrete evidence modes, execution priorities, judgment tradeoffs, local governance responsibilities, and risk terms",
    "Check Loopora fit and judgment sufficiency before authoring a Loop plan file",
    "Move through the planning conversation explicitly",
    "When an explicit message-only fallback returns `loop_recovery=continue_alignment_dialogue`",
    "Do not answer from host inference, workdir probes, Web page scraping",
    "Do not treat a detailed first prompt as confirmation",
    "those are alignment inputs, not a confirmed working agreement",
    "After explicit confirmation, create a complete Loopora `version: 1` candidate plan file",
    "Use message-only form only when the host cannot continue the main-session dialogue",
    "After explicit confirmation, run the bundle-file plan command directly",
    "Preserve evidence flow as reuse-first",
    "Builder produces durable task-owned proof artifacts",
    "Inspector first reads Builder handoffs and cited artifacts",
    "runs new commands only for missing, stale, ambiguous, conflicting, or distinct uncovered evidence gaps",
    "GateKeeper first cites supporting upstream evidence refs before any new proof command",
    "do not replace the interactive alignment path with a one-shot candidate-file path",
    "Use `message_cli_command` / `next_plan_cli_command` from recovery output as a diagnostic or fallback shape only",
    "If Loopora fit is false",
    "ask one focused question",
    "return a Web review prefill",
    "same Agent context binding / alignment_session_id",
    "put each user answer into the next message-only `--message`",
    "appends to that fallback conversation",
    "only a rough goal without Loopora fit reason, fake-done risk, evidence, or judgment tradeoff signal",
    "instead of synthesizing a complete READY candidate",
    "execution strategy",
    "what to build, prove, repair, narrow, expand, or defer first",
    "judgment tradeoffs",
    "local governance responsibilities",
    "owner, follow-up, or acceptance path",
    "notification, notification / subscription-deliverability, idempotency / duplicate-prevention, audit, permission, privacy / secrets-redaction, migration / rollback-integrity, compatibility / backward-compat, evaluation / eval-set, quality / human-review, ai / rag-grounding-tool-safety, incident / root-cause-repro, regression / monitoring-guard, release / feature-flag-rollout, external / provider-contract, compliance / kyc-aml-sanctions-screening, resilience / retry-timeout, access / authorization-policy-consistency, access / tenant-isolation, data / residency-regional-isolation, access / support-impersonation-breakglass, file-upload / storage-safety, data-import / validation-idempotency, concurrency / conflict-resolution, inventory / reservation-consistency, usage / quota-metering, tax / calculation-compliance, backup / restore-recovery, data / cdc-replication-consistency, audit / log-integrity-retention, cache / invalidation-consistency, search / index-consistency, data-lifecycle / deletion-retention, privacy / consent-preference-governance, analytics / event-integrity, experiment / assignment-consistency, async / job-lifecycle, queue / failure-recovery, schedule / timezone-recurrence, webhook / signature-replay-ordering, billing / ledger-reconciliation, payment / dispute-chargeback-lifecycle, payout / settlement-reconciliation, reporting / metric-reconciliation, identity / sso-assertion, identity / provisioning-role-mapping, auth / session-token-lifecycle, accessibility / a11y, locale / i18n",
    "billing / subscription-entitlement-proration",
    "do not let a bundle pass merely because it repeats one or two object words from the task",
    "Do not invent human judgment just to pass validation",
    "raw.legacy",
    "Do not pipe Loopora JSON, role wrappers, result wrappers, proof artifacts, or recovery payloads through `head`, `head -c`, `tail`, `sed`, Python string slicing, or other truncating filters",
    "read the complete compact JSON",
    "Candidate validation does not use a nested provider CLI",
    "ready_review_projection",
    "same-session run command",
    "`loop_recovery=plan_message_required`",
    "question_action",
    "recommended_reply_shape",
    "decision_impact",
    "message_source_policy",
    "message_cli_command",
    "draft working agreement",
    "do not author or repair a candidate file from that prompt until confirmation is explicit",
    "task_message_template",
    "first_task_message_example",
    "first_task_message_example_state",
    "first_task_handoff_policy",
    "debug_cli_example_command",
    "review_status",
    "after_review_slash_command",
    "run_blocked_until_web_review",
    "after_review_cli_command_status",
    "canonical `after_review_cli_command`",
    "after_review_cli_command",
    "Treat `after_web_review_cli_command` and legacy `after_review_command` as JSON compatibility diagnostics",
    "ready_slash_command",
    "ready_cli_command",
    "ready_next_step",
    "repair_slash_command",
    "repair_cli_command",
    "repair_cli_command_policy",
    "repair_reference",
    "repair_action",
    "agent_work_panel.next_action",
    "alignment session artifacts",
    "manifests",
    "rerun `repair_cli_command` exactly with `--json --compact-json`",
    "Do not replace it with `--json` alone",
    "do not pipe Loopora JSON through `head`, `head -c`, `tail`, `sed`, or Python slicing",
    "Loopora source/help output",
    "do not inspect alignment session artifacts",
    "run binary/PATH probes such as `which loopora`, `command -v loopora`, `type loopora`, or `echo $PATH`",
    "run `loopora diagnose`",
    "filesystem-wide discovery such as `find /`",
    "managed Candidate Bundle Skeleton",
    "repair_task_message",
    "preserves `repair_task_message` and `repair_focus`",
    "review_before_loop",
    "confirm that review summary and preview URL",
    "asks this Agent session to run both Loopora phases",
    "continue after the summary by invoking `/loopora-run` or `ready_cli_command`",
    "do not start the run from Web",
    "Do not use expert commands such as `loopora spec`, `loopora bundles`, or `loopora loops create`",
    "repair the plan file",
    "Loop preview",
    "Web review",
    "## Candidate Bundle Skeleton",
    "`loop`, `spec`, and `workflow` must be objects, not lists",
    "workflow.steps` is the list of step objects",
    "Each role definition must include `key`, `name`, `description`, `archetype`, `prompt_ref`, `prompt_markdown`, `posture_notes`, executor fields, `model`, and `reasoning_effort`",
    "Use literal `prompt_markdown: |`; do not use folded `>-`",
    "needs multi-round Loopora governance",
    "Buckets: Proven, Weak, Unproven, Blocking, Residual risk",
    "- Proven: name the exact evidence that proves the task",
    "put verified baseline, fixture, artifact, or run-context facts in Evidence Preferences or GateKeeper evidence_claims",
    "- Fail closed if: ...",
    "task-inspector",
    "First inspect Builder handoffs and cited task-owned artifacts",
    "Reuse fresh complete successful proof artifacts as primary evidence",
    "Inspect Builder artifacts first",
    "Inspect known upstream evidence refs, handoffs, and cited task-owned artifacts before running any new proof command",
    "Builder -> Inspector -> GateKeeper",
    "semantic lint expects bucket projection to reach Inspector posture and GateKeeper closure",
)

AGENT_ENTRY_LOOP_CONTRACT_SNIPPETS = (
    "## Purpose",
    "## Run Command",
    "## Recovery",
    "## Work Panel Use",
    "## Role Dispatch",
    "## Result Template",
    "## Proof Boundary",
    "## Failure Modes",
    "Enter Loopora's run stage",
    "top-level `summary`",
    "Do not pipe Loopora JSON, role wrappers, result wrappers, proof artifacts, or recovery payloads through `head`, `head -c`, `tail`, `sed`, Python string slicing, or other truncating filters",
    "Never append a shell filter such as `2>&1 | head -200`, `| tee ... | wc -l`, or `; wc -c ...`",
    "read the complete compact JSON",
    "not a `/tmp` path",
    "The same rule applies to any command output you later cite as proof",
    "run, resume, continue, keep going, close evidence gaps",
    "tell them to use `/loopora-plan` or Web review first",
    "Do not silently rewrite the Loop from `/loopora-run`",
    "failed `Skill` tool invocation with `disable-model-invocation` is an entry-visibility signal",
    "not permission to simulate `/loopora-run` through a generic `Agent` or `Task` call",
    "Do not inspect `$HOME/.claude`, global skill directories, Loopora manifests, binary/PATH probes",
    "`which loopora`, `command -v loopora`, `type loopora`, `echo $PATH`",
    "`loopora --version`, `loopora --help`, `loopora init claude`, `loopora agent claude check`",
    "Do not run the combined preflight `which loopora && loopora --version`",
    "directory-listing preflights such as `ls`",
    "the next Loopora Bash action should be the primary run/next/submit command returned by Loopora",
    "parent directories, or broad project/file discovery to verify the entry",
    "use host-native role `Agent` / `Task` dispatch only after Loopora Core returns a role `next_step`",
    "summary.agent_work_panel",
    "agent_work_panel:",
    "`state`, `current_role`, `target_agent`, `role_handoff_status`, `next_action`, `evidence_focus`, and `top_gaps`",
    "main Agent session",
    "Bash/tool/JSON output alone",
    "If a task or probe asks for runtime activity observation",
    "use the returned local Web origin to read `/api/runtime/activity`",
    "`run_url_status` / `run_url_web_start_command`",
    "save any snapshot you keep under a workdir-local artifact path, not `/tmp`",
    "Returned run URLs, timeline/evidence directories, ledgers, or post-exit file existence are diagnostics only",
    "loopora_host_dispatch",
    "role_dispatch.target_agent",
    "Do not read host role-agent config files, step context, step-contract, or result-template files in the main session as a substitute for dispatch",
    "only set `loopora_host_dispatch.actual_agent`, `native_tool_name`, `dispatch_mode=host_subagent`, or `inline=false` when a real host-native role call was observed",
    "role_dispatch.target_agent_config_exists",
    "judgment_contract",
    "next_step.judgment_contract",
    "next_step.required_coverage",
    "next_step.coverage_target_ids",
    "next_step.coverage_targets",
    "next_step.output_schema",
    "next_step.action_policy",
    "next_step.known_evidence_ids",
    "next_step.known_evidence_refs",
    "next_step.native_todo",
    "next_step.submit_hint.result_template_absolute_path",
    "Read the returned JSON, even if the command exits nonzero",
    "`loop_recovery=choose_recoverable_context`",
    "selection_hint",
    "runnable/non-runnable counts",
    "non-runnable choices' `preview_path`, `preview_url`, `preview_url_status`, `preview_url_web_start_command`, `validation_error`, `repair_focus`",
    "`loop_recovery=plan_first`",
    "Report `required_inputs`, `ask_user`, one main-session `question_action`, `recommended_reply_shape`, `decision_impact`, `example_user_reply`, `message_source_policy`, `message_cli_command`, and `next_plan_command`",
    "first_task_handoff_policy",
    "If the answer is only a rough goal",
    "rather than synthesizing a READY candidate",
    "`loop_recovery=active_run_conflict`",
    "`active_run_url`, `active_run_url_status`, and `active_run_url_web_start_command`",
    "`loop_recovery=finish_web_review`",
    "review_status",
    "run_blocked_until_web_review",
    "after_review_cli_command_status",
    "canonical `after_review_cli_command`",
    "Treat `after_web_review_cli_command` and legacy `after_review_command` as JSON compatibility diagnostics",
    "`loop_recovery=repair_candidate_plan_file`",
    "repair_cli_command_policy",
    "repair_reference",
    "next_repair_step",
    "agent_work_panel",
    "repair_action",
    "do not inspect Loopora source/help output",
    "alignment session artifacts",
    "manifests",
    "filesystem-wide discovery such as `find /`",
    "repair_task_message",
    "preserves `repair_task_message` and `repair_focus`",
    "Do not collapse these recovery states into a generic",
    "expert commands such as `loopora spec`, `loopora bundles`, or `loopora loops create`",
    "terminal `task_verdict_status` / `task_verdict_summary`",
    "If the command returns `loop_recovery`, report that recovery path and stop",
    "loopora_result_contract",
    "The submitted filled file should contain exactly `loopora_host_dispatch` and `result`",
    "remove that helper block from the filled copy before submit",
    "native_trace_contract",
    "Do not hand-write the wrapper from memory",
    "Fill only the `result` object",
    "Ask the role agent to return one raw JSON object only",
    "no Markdown fence, prose preface, code block, or trailing explanation",
    "summary.next_role_dispatch_message",
    "summary.next_step.role_dispatch_message",
    "verbatim as the whole role prompt",
    "Use this exact string as the whole Agent/Task prompt",
    "prompt input itself must be the compact dispatch message",
    "Do not add wrapper framing before or after it",
    "prepend `You are running as`",
    "append `Do the following`",
    "Never append extra paragraphs after the compact dispatch message",
    "task instructions, proof commands, proof artifact path examples",
    "Never replace the compact dispatch message with a custom prompt beginning with phrases such as `You are running as the Loopora ... role agent`",
    "build a compact role-dispatch message",
    "step-contract path",
    "Do not paste full CLI JSON",
    "full schemas, full evidence ledger rows",
    "hand-written result-wrapper examples",
    "role call returns no wrapper / no structured output",
    "do not construct `result` from main-session file reads, reruns, role-agent config text, or observations",
    "Do not require read-only role agents",
    "submit_repair=repair_result_json",
    "summary.task_proven",
    "summary.next_step.iteration_repair",
    "next_agent_command",
    "task_proven",
    "task_outcome",
    "lifecycle_vs_task",
    "summary.continuation",
    "next_step.iteration_repair",
    "next_step.submit_hint.command",
    "Do not append `| head`, `| tail`, `| sed`, `| python -c`, `| jq`, `| grep`, `| wc`, `| tee`, `2>&1 | ...`, or `; wc -c ...` to submit",
    "do not stage submit JSON in `/tmp`",
    "run.task_verdict",
    "task_next_action",
    "task_next_action.kind",
    "task_next_action.next_loop_command",
    "continue_evidence",
    "already_passed",
    "retry_lifecycle_failure",
    "submitted_step.evidence_refs",
    "submitted_step.handoff_absolute_path",
    "submitted_step.coverage_result_scope",
    "coverage_after_submit",
    "submitted_step.blocking_items",
    "submitted_step.recommended_next_action",
    "next_step.prompt",
    "StepInstruction context path",
    "native dispatch unavailable",
)

AGENT_ORCHESTRATOR_CONTRACT_SNIPPETS = (
    "compact role-dispatch message",
    "summary.next_role_dispatch_message",
    "summary.next_step.role_dispatch_message",
    "verbatim as the whole role prompt",
    "Use this exact string as the whole Agent/Task prompt",
    "prompt input itself must be the compact dispatch message",
    "Do not add wrapper framing before or after it",
    "prepend `You are running as`",
    "append `Do the following`",
    "Never append extra paragraphs after the compact dispatch message",
    "StepInstruction context path",
    "step-contract path",
    "result-template path",
    "coverage target IDs",
    "open those local paths",
    "full prompt, output schema, judgment contract",
    "Do not paste full CLI JSON",
    "next_step.native_todo",
    "next_step.submit_hint.result_template_absolute_path",
    "native_trace_ref",
    "loopora_result_contract",
    "schema-shaped `result` scaffold",
    "replace every `null` placeholder",
    "Do not ask read-only role agents to write Loopora outbox result files",
    "submit_repair=repair_result_json",
    "task_next_action.kind=continue_evidence",
    "task_next_action.kind=already_passed",
    "task_next_action.kind=retry_lifecycle_failure",
    "no role invocation starts",
    "no observable role output",
    "compact role-dispatch message",
    "open those local paths",
    "large file contents",
    "same proof-output contract as role agents",
    "Proof command output rule",
    "discovery, directory-listing, context-check",
    "do not stage it in `/tmp`",
    "count-only probes",
    "do not replace it with `ls ... | head`",
    "If a proof artifact is empty or shorter than expected",
)

EXPECTED_NATIVE_PACKAGING = {
    "behavior_source": "loopora_core_and_managed_references",
    "host_entries": "generated_thin_project_local_packaging",
    "projection_policy": "generated_projections_caches_and_marketplace_metadata_are_not_canonical_behavior",
    "component_export": "prompt_wrappers_cross_host_skill_exports_and_external_skill_installers_are_guidance_not_adapter_parity_or_install_proof",
    "install_scope": "project_local_no_global_marketplace_or_skill_cache",
    "entry_visibility": "adapter_project_entries_checked_not_global_skill_sync_assumed",
    "shadow_policy": "stale_duplicate_or_shadow_entries_are_visibility_risks_not_loopora_proof",
    "registry_policy": "remote_marketplaces_are_discovery_not_runtime_dependency_or_proof",
    "link_policy": "global_or_external_symlinks_are_hints_not_loopora_entry_proof",
    "runtime_bundle": "entries_roles_references_and_state_checked_together",
    "manifest": "managed_files_sha256_manifest",
    "drift_check": "loopora_check_reports_missing_stale_or_unowned_files",
    "update_policy": "explicit_check_or_init_only_no_background_auto_update",
    "repair": "regenerate_loopora_managed_packaging_only",
}

EXPECTED_NATIVE_CONTEXT_LOADING = {
    "entry_prompt": "thin_dispatcher",
    "summary_first": [
        "summary",
    ],
    "reference_loading": "on_demand_from_reference_paths",
    "full_payload": "open_after_compact_summary",
    "host_memory": "host_owned_hint_not_loopora_context_or_evidence",
    "memory_store": "external_memory_stores_indexes_and_memory_mcp_are_hints_not_loopora_context_or_proof",
    "template_context": "host_command_templates_playbooks_and_dynamic_prompts_are_hints_not_loopora_reviewed_workflow",
    "workflow_kits": "external_spec_workflows_prd_packs_quality_gate_recipes_and_workflow_kits_are_guidance_not_loopora_reviewed_workflow_install_proof_or_evidence",
    "role_catalogs": "external_agent_catalogs_subagent_libraries_and_role_marketplaces_are_selection_hints_not_loopora_role_contract_or_policy",
    "compaction_context": "host_compaction_summaries_are_hints_not_loopora_context_or_proof",
    "host_context": "host_loaded_skills_commands_agents_editor_context_and_ide_bridges_are_hints_not_loopora_context_contract_or_evidence",
    "catalog_context": "marketplace_catalogs_and_uninstalled_components_are_not_loopora_context_or_proof",
}

EXPECTED_NATIVE_PERMISSION_BOUNDARY = {
    "policy_owner": "host_agent_and_user",
    "loopora_policy": "do_not_bypass_or_downgrade_host_permissions",
    "role_scope": "use_host_native_role_tool_allowlists",
    "approval_prompts": "pause_for_host_approval_or_report_blocked",
    "mode_switching": "host_agent_user_owned_not_changed_by_loopora",
    "automation": "auto_approvers_full_access_and_no_sandbox_are_host_opt_in_not_loopora_policy",
    "sandbox_runners": "external_containers_devcontainers_microvms_and_remote_runners_are_host_isolation_not_loopora_workspace_permission_or_proof",
    "security_guardrails": "external_security_scanners_guardrails_and_agent_firewalls_are_host_controls_not_loopora_permission_policy_or_evidence",
    "deny_rules": "respect_host_deny_rules_before_loopora_submit",
    "proof_boundary": "approval_is_not_task_evidence",
}

EXPECTED_NATIVE_TOOLING_BOUNDARY = {
    "mcp_servers": "host_owned_not_installed_or_enabled_by_loopora",
    "external_tools": "use_host_available_tools_without_relaxing_permissions",
    "tool_outputs": "proof_only_when_submitted_as_loopora_evidence",
}

EXPECTED_NATIVE_OBSERVABILITY = {
    "agent_activity": "host_status_or_compact_summary_only",
    "web_view": "observe_evidence_gaps_and_verdicts",
    "permission_prompts": "host_agent_owns_approval_flow",
    "hook_events": "observation_only_until_submitted_as_loopora_evidence",
    "hook_protocol": "adapter_specific_no_cross_host_parity_assumption",
    "hook_runners": "external_hook_runners_are_opt_in_host_automation_not_loopora_dispatch",
    "statusline_metrics": "host_statusline_usage_cost_context_and_git_metrics_are_observation_not_loopora_proof",
    "task_trackers": "external_task_managers_todos_backlogs_and_subagent_statuses_are_coordination_not_loopora_lifecycle_or_proof",
    "remote_controls": "ci_actions_pr_bots_comment_triggers_dashboards_webhooks_and_background_consoles_are_host_control_not_loopora_activation_dispatch_or_proof",
    "diagnostic_traces": "external_trace_viewers_api_proxies_session_recorders_and_usage_analyzers_are_diagnostics_not_loopora_evidence_or_verdict",
    "progress_signal": "activity_status_is_not_task_proof",
    "proof_signal": "loopora_evidence_refs_and_task_verdict",
}

EXPECTED_NATIVE_EXPERIENCE_CAPABILITIES = {
    "role_dispatch_guidance": "managed_entries_name_the_host_native_role_agent_and_stop_before_inline_submit",
    "todo_guidance": "native_todo_should_create_or_update_host_todo_when_available_not_evidence",
    "user_question_guidance": "ask_user_routes_missing_loop_judgment_to_main_agent_session",
    "native_trace_optional": "preserve_official_subagent_or_task_trace_when_available_do_not_invent",
    "technical_handoff_paths": "context_step_contract_result_template_and_submit_command_remain_available_below_work_panel",
}
