from __future__ import annotations

from pathlib import Path


DESIGN_DIR = Path(__file__).resolve().parents[3] / "design"


def _assert_all_terms_present(text: str, terms: tuple[str, ...]) -> None:
    missing = [term for term in terms if term not in text]
    assert missing == [], missing


def _design_text(path: str) -> str:
    return (DESIGN_DIR / path).read_text(encoding="utf-8")


def assert_contributor_first_use_web_and_public_contract_anchors_are_current() -> None:
    contracts = _design_text("contracts.md")
    domain_workflows = _design_text("domain-workflow-contracts.md")
    service_boundaries = _design_text("service-boundaries.md")
    design_sources = (_design_text("README.md"), contracts, domain_workflows, service_boundaries)
    _assert_all_terms_present(
        contracts,
        (
            "Contributor PR evidence treats the default-fast gate as both verification and generated-artifact cleanup",
            "final stage-labeled `--pr-evidence` Markdown block as the main local evidence",
            "decision-scope evidence from the final copyable PR evidence block",
            "final default-fast result, package-build cleanup state",
            "Contributor package-build cleanup",
            "Contributor package-build content gate",
            "Public changelog and release notes",
            "Public governance and maintainer decisions",
            "Public community standards",
            "Contributor default-fast step order",
            "Dev-check decision surface",
            "Dev-check changed-file recommendation scope",
            "Dev-check changed-file recommendation readability",
            "Focused evidence guide",
            "Focused evidence first-use and Agent Native",
            "Focused evidence alignment and core execution",
            "Focused evidence runtime scope",
            "Focused evidence collaboration scope",
            "Dev-check report flow",
            "Dev-check focused PR evidence handoff",
            "Dev-check list planning evidence boundary",
            "Pull request evidence",
            "Pull request evidence checklist",
            "Pull request final evidence checklist",
            "Repository collaboration",
            "Repository feature intake",
            "Repository collaboration judgment",
            "Dev-check PR evidence prompt",
            "Dev-check PR evidence detail ownership",
            "Dev-check PR evidence list reminder",
            "Dev-check PR evidence copyable summary",
            "Dev-check focused pass PR evidence action",
            "Dev-check recommendation-free PR evidence",
            "Dev-check PR evidence JSON surface",
            "Focused recommendation list usability",
            "Focused run result usability",
            "Dev-check next-action guide summaries",
            "Focused guide command target validity",
            "Focused recommendation pattern boundary",
            "Dev-check option recovery",
            "Dev-check scoped recovery commands",
            "Local asset diagnostics",
            "Local asset registry path boundary",
            "Event redaction audit",
            "Event redaction command positioning",
            "Plain `loopora dev check --list` output is a PR evidence decision surface",
            "record recommended guide IDs plus ignored and unmatched changed-file lines",
            "First-use routing",
            "First-use router path order",
            "replace stale visible/navigation context with the pending input",
            "Source-checkout command boundary",
            "Project-entry workdir command boundary",
            "Fit decision guide",
            "completed strong-fit reviews reveal ready/blocked routes",
            "Fit decision automation surface",
            "readiness-scope fields",
            "Fit decision first-plan handoff",
            "read-only local route action outside review/setup/direct-path gates",
            "targetless direct-path decisions still expose route-only support",
            "It keeps review-complete `/loopora-plan` message readiness separate from target-project setup executability",
            "blocked by target-project state, not by missing review inputs",
            "completed-review route previews omit `check_fit_first`",
            "embedded fit guidance route/kind summaries mirror the top-level start route",
            "complete-review plain output stops repeating unanswered setup questions",
            "plain first-use next actions use readable labels that separate ready-now route choices",
            "JSON publishes ready-now/dependent readiness fields beside stable next/route action kinds",
            "Doctor readiness report",
            "Doctor plain readiness separation",
            "Doctor plain next-action prioritization",
            "Doctor no-ready-entry first-use handoff",
            "preserves that target in the fit command",
            "Doctor JSON automation surface",
            "Compact identity diagnostics",
            "Public support diagnostics",
            "Public support diagnostics redaction",
            "Public support CLI guidance",
            "keeps readiness-aware posting",
            "targetless previews",
            "marks the public issue bundle as preferred evidence",
            "requested fallbacks",
            "tolerates nonzero public-doctor",
            "Public support CLI localization",
            "Public support shared Web guidance",
            "standalone Support can set/recall target context",
            "surfaces/clears transient feedback",
            "mirror readiness/status",
            "public issue bundles first",
            "syncs Tools/Web target gates",
            "clears stale manual copies",
            "Serve and Web auth readiness",
            "Web remote auth fail-closed boundary",
            "Web human auth token-form boundary",
            "Web token auth compatibility inputs",
            "Web network URL and bind recovery",
            "Web port validation and doctor bind probes",
            "Web network auth gate",
            "Web network auth construction gate",
            "Web auth URL cleanup",
            "Web forwarded-query sensitive-key stripping",
            "Web auth automation and challenge boundary",
            "Web network host-path actions",
            "Web/App state recovery",
            "Web/App reset recovery action",
            "Web/App blocked-start recovery",
            "Web/App port-conflict recovery flags",
            "Web Tools readiness",
            "Web Tools readiness blockers",
            "Web Tools stale-target mutation gate",
            "Web Tools target preference scope",
            "Web Tools recent target ownership",
            "Web Tools target picker mode",
            "Web Tools resolved target propagation",
            "Web Tools command source boundary",
            "Web Tools blank-target mutation gate",
            "Adapter setup recovery reports",
            "Adapter setup human and JSON split",
            "adapter-choice command lists",
            "compact recovery summaries",
            "Adapter setup readiness reuse",
            "CLI command group help-first navigation",
            "CLI adapter group target preview",
            "CLI adapter group target propagation",
            "CLI adapter group target repair gate",
            "CLI unsupported adapter target recovery",
            "adapter-choice entry commands",
            "Agent adapter command identity recovery",
            "Agent adapter unsupported-name recovery",
            "readable plain labels",
            "First-use readiness aggregate",
            "First-use readiness interpretation",
            "uniquely detected current host may be preselected",
            "Shell recovery for Agent slash-command misuse stays route-aware and readiness-first",
            "surface Fit Guide/Web choices for users outside an Agent session before same-Agent setup",
            "First-use Web-start recovery actions",
            "First-use Web-start suggestion boundary",
            "Target-directory recovery order",
            "Shared target-directory prerequisite",
            "Target-directory blocked surface coverage",
            "Target-directory compose surface coverage",
            "Target-directory recovery output shape",
            "Target-directory fail-closed boundary",
            "Root help points users to Start/Fit `--details` for the complete Fit Guide/Web",
            "current-host same-Agent, import/manual expert, and existing-work choice model",
            "placeholder-safe support guidance",
            'disposable temporary Web preview with `LOOPORA_HOME="$(mktemp -d)" <current Loopora CLI entry> serve ...`',
            "current CLI entry such as source-checkout `uv --directory <Loopora checkout> run loopora`",
            "adapter alternatives such as codex/claude/opencode are exposed as choices or notes",
            "avoid duplicated command prefixes and inline shell comments",
            "First-use start guide",
            "`loopora start` is read-only",
            "preserves target context",
            "Plain output hides routes until target and review gates are ready",
            "plain ready/blocked route summaries",
            "targetless choose-workdir next actions preserve the current CLI entry/language",
            "route-guide option wording",
            "route/support commands preserve target workdir and language selection",
            "root CLI help is the shell-level first-use router",
            "presents Web continuation before same-Agent setup",
            "present the outside-Agent Fit Guide/Web choices path before same-Agent setup",
            "outside-Agent versus current-host distinction and the READY follow-up rule",
            "The start and fit default plain outputs use progressive disclosure",
            "one recommended executable next action",
            "`--details` preserves the complete human-readable fit record",
            "`--json` preserves the full structured contract unchanged",
            "The default root command table is ordered as `start`, `fit`, `demo`, `serve`, `init`, `doctor`, then `support`",
            "contributor local-checks entry stays visible",
            "advanced/internal commands stay reachable through their own help and hidden from the default first-use table",
            "completed strong-fit reviews present Fit Guide/Web choices first",
            "local loopback can be opened directly as the Fit Guide and Web choices entry",
            "Plain CLI leads with independent Web continuation or same-Agent setup",
            "Tools readiness renders the same Web start/recovery actions with copy controls",
            "same Web post-open choice model as CLI first-use routers",
        ),
    )
    _assert_all_terms_present(
        contracts,
        (
            "Support policy routes usage/setup questions",
            "linked bug/feature templates",
            "private security reporting",
            "Public issue triage",
            "Public issue triage interpretation",
            "Public bug report evidence",
            "Public bug identity/environment fallback",
            "Public bug report triage semantics",
            "Public support and security routing",
            "Public security private-reporting boundary",
            "`loopora support`",
            "Public issue support and redaction boundary",
            "Public issue bundle skim summary",
            "Public readiness command guidance",
            "Public readiness report redaction boundary",
            "Public feature request evidence",
            "Public issue templates surface support/security routing",
            "placeholder-safe command shapes",
            "report-only target-status interpretation",
            "Public package metadata",
            "Public package identity and dependency metadata",
            "no-license-declared boundary remains explicit in package metadata and public README adoption docs",
            "Public package no-license boundary",
            "Public README adoption status",
            "completed strong-fit reviews present Fit Guide/Web choices first",
            "route same-Agent users through the uniquely detected current Codex/Claude Code/OpenCode host",
            "Recovery commands expose adapter-choice install/check entries",
            "reports `ready` only when `/loopora-plan` handoff is executable",
            "READY preview review before same-Agent `/loopora-run` while Fit Guide/Web choices continue in Web",
            "Ordinary Web conversation remains independent",
            "First-use Web executable recovery controls",
            "First-use App-state executable recovery controls",
            "Public README adoption docs surface project status early",
            "source-checkout install boundary",
            "empty Home first-run path preserves the same decision order as CLI/docs",
            "Web creation routes",
            "Web empty-state creation choices",
            "Web empty-state continuation path",
            "Web creation-choice handoff",
            "Web creation-choice continuation handoff",
            "Web creation-choice continuation panels",
            "Web conversation progressive first turn",
            "Web Home attention",
            "Web Home attention ordering",
            "Web Home attention action semantics",
            "Web run-start recovery",
            "Web recorded-result verdict boundary",
            "Web recorded-result recovery",
            "Web Run-detail unrecorded evidence actions",
            "Web Run-detail recorded evidence posture",
            "Web Agent-native start boundary",
            "Web action recovery",
            "Web revision preflight recovery",
            "Web active-action feedback",
            "Web queued-stop and delete feedback",
            "Web compose validation recovery",
            "Web structured recovery panels",
            "Web recovery action control consistency",
            "Web recovery route ownership",
            "Web browser structured recovery preservation",
            "Web browser recovery action affordances",
            "Web file path semantics",
            "Web file path error semantics",
            "Web navigation local links",
            "Web navigation asset-link fallback",
            "Web navigation target context",
            "Web return target workdir recovery",
            "Web composer support return propagation",
            "Web composer support close-back",
            "Web composer return-token stripping",
            "Web navigation feedback markers",
            "Web workbench return context",
            "Web workbench compatibility returns",
            "Web shared interaction primitives",
            "Web destructive interaction confirmation",
            "Web shared primitive ownership",
            "Web shared clipboard fallback coverage",
            "Web shared clipboard fallback ownership",
            "Web Run-detail projection",
            "Web Run-detail raw-free boundary",
            "Web Run-detail stale action recovery",
            "Web run-start retry guidance",
            "Web run-start retry semantics",
            "Web run-start recovery URL",
            "Web request failure boundary",
            "Web known-error JSON semantics",
            "Web known-error rendering boundary",
            "Web unsafe redirect fallback",
            "Web token-stripped return paths",
            "Evidence manifest projection",
            "Evidence manifest stable coverage refs",
            "Evidence manifest dynamic-check dedupe",
            "Dual entry peer starts",
            "Dual entry create-choice starts",
            "Dual entry specific-route exceptions",
            "Dual entry context carryover",
            "Dual entry target-context display",
            "Dual entry navigation context preservation",
            "Dual entry session-derived context preservation",
            "Dual entry entity-derived context",
            "Dual entry import-link context",
            "Dual entry session URL identity",
            "Dual entry stale-session recovery",
            "Dual entry legacy deep links",
            "Dual entry Agent/Web ownership",
            "Dual entry Agent command identity",
            "Dual entry App-home command normalization",
            "Dual entry local Web URL availability",
            "Context choice resolution",
            "Context choice ambiguity recovery",
            "Context choice distinguishing metadata",
            "Context choice status semantics",
            "Context choice review/repair status semantics",
            "Context choice terminal recovery",
            "Context choice runnable commands",
            "Context choice Agent command quoting",
            "Agent Native submit hint workdir resolution",
            "Context choice dispatch-unavailable",
            "Context choice dispatch-unavailable no-workdir fallback",
            "Context choice preview availability",
            "Context choice preview URL readiness",
            "Agent Native current-step recovery",
            "Agent Native current-step choice commands",
            "Agent Native current-step READY routing",
            "Agent entry installation as a setup action rather than the default first click",
            "Same-Agent first-use vocabulary",
            "Same-Agent generic execution exclusion",
            "Same-Agent outside-Agent path placement",
            "use same-Agent project-entry wording",
            "same-Agent setup as the second path for users already in an Agent",
            "Same-Agent first-use order",
            "Same-Agent run-after-ready boundary",
            "ask users to keep the adapter matching the current host rather than recommending one adapter",
            "must not be framed as generic Agent execution",
            "Empty saved-loop libraries, returning Home states, and Loop detail no-run history keep",
            "Home returning priority",
            "Home passive recent priority",
            "Home saved-loop fallback priority",
            "Home target scope",
            "Home active Web conversation attention",
            "Home active attention identity",
            "Home create-choice existing-work cards",
            "Home create-choice existing-work actions",
            "Returning Home states with existing work keep the creation-choice path visible",
            "Agent-native saved Loop rerun surfaces keep host-Agent ownership visible",
            "same-host-Agent handoff",
            "Agent-native candidate semantic lint and repair hints",
            "compatible with legacy `agent-first candidate` text",
            "Agent-native plan files route users to the same-Agent run guide",
            "Agent-native Loops keep same-host-Agent handoff instead of Web start",
            "Web creation-choice page hero and card order make Web conversation the primary default",
            "same-Agent setup as the second path",
            "Hash-linked disclosure panels open on arrival only when continuation routes to a collection",
            "Fit Guide Web start handoff gate",
            "an explicit direct-path decision applies to every Loopora creation start on the creation-choice page",
            "Direct-path-blocked starts are disabled visually, for pointer activation, and for keyboard traversal",
            "Fit Guide wrong-project recovery",
            "Creation-choice and direct Web conversation handoff recovery expose finish-fit-review with the source project preserved across `workdir` and `alignment_workdir` URL contexts",
            "Fit Guide same-Agent setup handoff target",
            "Web conversation session switching",
            "Web active conversation switch guard",
            "Web same-target compose return",
            "Fit Guide handoff same-project checks",
            "Browser handoff target checks use the shared frontend same-project comparison rather than raw displayed path strings",
            "Same-Agent setup exposes a Fit Guide draft as a paste-ready Agent brief only after the fit-review inputs are complete",
            "Web conversation begins from one task goal",
        ),
    )
    assert "implementation ownership boundaries" in service_boundaries
    assert "Product behavior, public contracts, and user-path claims stay in `contracts.md`" in service_boundaries
    assert "`LooporaService` remains the only compatibility pass-through facade" in service_boundaries
    assert "### Service Composition" in service_boundaries
    assert "### Alignment Context And Compiler" in service_boundaries
    assert "### Executor Boundaries" in service_boundaries

    for source in design_sources:
        assert "bundle library" not in source.lower()
        assert "Web 只是观察面" not in source
