from __future__ import annotations


def _assert_bundle_task_routing_design_inventory(sources: dict[str, str]) -> None:
    for module_name in (
        "executor_alignment_bundle_task_routing.py",
        "executor_alignment_bundle_task_spec_scaffolds.py",
        "executor_alignment_bundle_task_spec_scaffolds_commercial.py",
        "executor_alignment_bundle_task_spec_scaffolds_data.py",
        "executor_alignment_bundle_task_spec_scaffolds_operations.py",
        "executor_alignment_bundle_task_spec_scaffolds_product.py",
        "executor_alignment_bundle_task_spec_scaffolds_product_engagement.py",
        "executor_alignment_bundle_task_spec_scaffolds_product_operations.py",
        "executor_alignment_bundle_task_spec_scaffolds_product_search_ai.py",
        "executor_alignment_bundle_task_spec_scaffolds_trust.py",
        "executor_alignment_bundle_task_spec_scaffolds_trust_access.py",
        "executor_alignment_bundle_task_spec_scaffolds_trust_governance.py",
        "executor_alignment_bundle_task_spec_scaffolds_trust_secrets.py",
        "executor_alignment_bundle_task_spec_notes.py",
        "task-spec-workflow-notes.json",
        "executor_alignment_bundle_task_spec_scaffold_templates.py",
        "task-spec-scaffold-templates.json",
        "executor_alignment_bundle_task_predicates.py",
        "executor_alignment_task_predicates.py",
        "executor_alignment_task_predicates_commercial.py",
        "executor_alignment_task_predicates_commercial_billing.py",
        "executor_alignment_task_predicates_commercial_cross_domain.py",
        "executor_alignment_task_predicates_commercial_metrics.py",
        "executor_alignment_task_predicates_commercial_payments.py",
        "executor_alignment_task_predicates_data.py",
        "executor_alignment_task_predicates_data_cross_domain.py",
        "executor_alignment_task_predicates_data_ingest.py",
        "executor_alignment_task_predicates_data_lifecycle.py",
        "executor_alignment_task_predicates_data_migration.py",
        "executor_alignment_task_predicates_data_read_models.py",
        "executor_alignment_task_predicates_data_resilience.py",
        "executor_alignment_task_predicates_operations.py",
        "executor_alignment_task_predicates_product.py",
        "executor_alignment_task_predicates_product_cross_domain.py",
        "executor_alignment_task_predicates_product_engagement.py",
        "executor_alignment_task_predicates_product_operations.py",
        "executor_alignment_task_predicates_product_search_ai.py",
        "executor_alignment_task_predicates_trust.py",
        "executor_alignment_task_predicates_trust_access.py",
        "executor_alignment_task_predicates_trust_cross_domain.py",
        "executor_alignment_task_predicates_trust_governance.py",
        "executor_alignment_task_predicates_trust_secrets.py",
    ):
        assert module_name in sources["contracts"]
        assert module_name in sources["service_boundaries"]
