from __future__ import annotations

from pathlib import Path

from loopora.bundles import (
    lint_alignment_bundle_generation_metadata,
    lint_alignment_bundle_generation_text,
    lint_alignment_bundle_semantics,
    load_bundle_text,
)
from loopora.executor_fake_payloads import alignment_bundle_yaml


def test_alignment_generated_metadata_omits_lineage_fields(sample_workdir: Path) -> None:
    valid_yaml = alignment_bundle_yaml(str(sample_workdir.resolve()))
    assert lint_alignment_bundle_generation_text(valid_yaml) == []
    assert lint_alignment_bundle_generation_metadata(valid_yaml) == []

    lineage_yaml = valid_yaml.replace(
        '  description: "Bundle generated by the Web alignment flow."\n',
        '  description: "Bundle generated by the Web alignment flow."\n  source_bundle_id: "source_bundle_old"\n  revision: 2\n',
        1,
    )

    assert lint_alignment_bundle_generation_metadata(lineage_yaml) == [
        "Web alignment generated bundles must omit metadata.source_bundle_id and metadata.revision; "
        "source context is temporary and final bundles are standalone candidates"
    ]
    semantic_issues = lint_alignment_bundle_semantics(load_bundle_text(lineage_yaml))
    assert (
        "Web alignment bundles must not encode metadata.source_bundle_id; source context is temporary and final bundles are standalone candidates"
    ) in semantic_issues


def test_alignment_generated_bundle_text_must_be_raw_yaml(sample_workdir: Path) -> None:
    valid_yaml = alignment_bundle_yaml(str(sample_workdir.resolve()))
    yaml_with_internal_fence = valid_yaml.replace(
        "Leave concrete handoffs and evidence references for downstream review.",
        "Leave concrete handoffs and evidence references for downstream review.\n\n      ```text\n      internal example\n      ```",
        1,
    )

    fenced_issues = lint_alignment_bundle_generation_text(f"```yaml\n{valid_yaml}```")
    prefixed_issues = lint_alignment_bundle_generation_text("Here is the bundle:\n" + valid_yaml)
    comment_prefixed_issues = lint_alignment_bundle_generation_text("# Here is the bundle\n" + valid_yaml)

    assert lint_alignment_bundle_generation_text(yaml_with_internal_fence) == []
    assert "Web alignment generated bundle_yaml must be one raw YAML document, not markdown-fenced output" in fenced_issues
    assert "Web alignment generated bundle_yaml must start with version: 1" in fenced_issues
    assert prefixed_issues == ["Web alignment generated bundle_yaml must start with version: 1"]
    assert comment_prefixed_issues == ["Web alignment generated bundle_yaml must start with version: 1"]
